In [ ]:
#Import pandas 
import pandas as pd

In [ ]:
#Load dataset
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\pandas\customers_clean.csv")

In [ ]:
#Displays the dataframe 
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        97 non-null     str
 1   first_name         97 non-null     str
 2   last_name          97 non-null     str
 3   gender             97 non-null     str
 4   age                97 non-null     int64
 5   city               97 non-null     str
 6   country            97 non-null     str
 7   signup_date        97 non-null     str
 8   employment_status  97 non-null     str
 9   annual_income      97 non-null     float64
 10  credit_score       97 non-null     float64
 11  risk_level         97 non-null     str
dtypes: float64(2), int64(1), str(9)
memory usage: 9.2 KB

In [ ]:
#Convert signup date to datetime data type
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        97 non-null     str
 1   first_name         97 non-null     str
 2   last_name          97 non-null     str
 3   gender             97 non-null     str
 4   age                97 non-null     int64
 5   city               97 non-null     str
 6   country            97 non-null     str
 7   signup_date        97 non-null     datetime64[us]
 8   employment_status  97 non-null     str
 9   annual_income      97 non-null     float64
 10  credit_score       97 non-null     float64
 11  risk_level         97 non-null     str
dtypes: datetime64[us](1), float64(2), int64(1), str(8)
memory usage: 9.2 KB

In [24]:
#Extract the signup year
df["signup_year"] = df["signup_date"].dt.year

In [25]:
#Extract the signup month
df["signup_month"] = df["signup_date"].dt.month_name()

In [26]:
#Extract the day
df["signup_day"] = df["signup_date"].dt.day

In [27]:
#Extract weekday
df["signup_weekday"] = df["signup_date"].dt.day_name()

In [28]:
#Extract the quarter
df["signup_quarter"] = df["signup_date"].dt.quarter

In [35]:
#Calculate Days since signup
#Today's date - Signup Date = Number of Days
df["days_since_signup"] = (
    pd.Timestamp.today()- df["signup_date"]
).dt.days

df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,days_since_signup
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium,2024,October,26,Saturday,4,626
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium,2024,August,20,Tuesday,3,693
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium,2024,July,30,Tuesday,3,714
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium,2024,May,16,Thursday,2,789

In [36]:
#Which month had the most signups?
df["signup_month"].value_counts()

signup_month
March        17
May          16
February     12
April        11
January       9
December      7
June          6
July          5
October       5
August        4
November      3
September     2
Name: count, dtype: int64

In [37]:
#Which weekday sees the highest signup volume?
df["signup_weekday"].value_counts()

signup_weekday
Tuesday      21
Friday       16
Saturday     14
Monday       14
Thursday     13
Wednesday    12
Sunday        7
Name: count, dtype: int64

In [ ]:
#Are signups increasing over time?
df.groupby("signup_year").size()

signup_year
2024    71
2025    26
dtype: int64

In [ ]:
#How long has each customer been with FinPay?
df[["customer_id","signup_date","days_since_signup"]]

   customer_id signup_date  days_since_signup
0         C001  2024-03-12                854
1         C002  2024-02-17                878
2         C003  2024-04-22                813
3         C004  2025-05-05                435
4         C005  2025-02-17                512
..         ...         ...                ...
92        C096  2024-10-26                626
93        C097  2025-03-15                486
94        C098  2024-08-20                693
95        C099  2024-07-30                714
96        C100  2024-05-16                789

[97 rows x 3 columns]

In [ ]:
#Which customers joined in 2025?
df[df["signup_year"]==2025]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,days_since_signup
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low,2025,March,29,Saturday,1,472
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low,2025,April,4,Friday,2,466
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low,2025,March,16,Sunday,1,485
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High,2025,March,21,Friday,1,480
19,C020,Noor,Qureshi,Female,33,Mecca,Saudi Arabia,2025-01-21,Student,92730.0,659.0,Medium,2025,January,21,Tuesday,1,539
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914.0,548.0,Low,2025,February,17,Monday,1,512
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High,2025,March,18,Tuesday,1,483
33,C037,Noor,Syed,Male,55,Dammam,Saudi Arabia,2025-04-22,Unknown,67154.0,568.0,Medium,2025,April,22,Tuesday,2,448
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low,2025,April,28,Monday,2,442
39,C043,Aisha,Ansari,Male,42,Mecca,Saudi Arabia,2025-03-28,Self-Employed,80515.0,621.0,Low,2025,March,28,Friday,1,473
40,C044,Omar,Hussain,Male,31,Dammam,Saudi Arabia,2025-02-04,Self-Employed,105055.0,636.0,Low,2025,February,4,Tuesday,1,525
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium,2025,March,25,Tuesday,1,476
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low,2025,February,15,Saturday,1,514
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High,2025,February,14,Friday,1,515
54,C058,Fatima,Farooq,Female,55,Khobar,Saudi Arabia,2025-04-04,Salaried,164433.0,730.0,Medium,2025,April,4,Friday,2,466
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low,2025,March,14,Friday,1,487
59,C063,Fatima,Shaikh,Female,46,Mecca,Saudi Arabia,2025-01-17,Student,97812.0,749.0,Low,2025,January,17,Friday,1,543
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low,2025,February,3,Monday,1,526
68,C072,Zaid,Ansari,Male,39,Mecca,Saudi Arabia,2025-02-16,Salaried,50766.0,677.0,High,2025,February,16,Sunday,1,513
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High,2025,January,10,Friday,1,550
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High,2025,January,23,Thursday,1,537
87,C091,Noor,Farooq,Male,34,Dammam,Saudi Arabia,2025-02-07,Student,91857.0,717.0,Low,2025,February,7,Friday,1,522
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low,2025,May,1,Thursday,2,439
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486

In [43]:
#Which customers joined in Quarter 1?
df[df["signup_quarter"]==1]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,days_since_signup
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low,2025,March,29,Saturday,1,472
10,C011,Fatima,Ansari,Female,45,Khobar,Saudi Arabia,2024-03-14,Self-Employed,76603.0,686.0,High,2024,March,14,Thursday,1,852
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low,2025,March,16,Sunday,1,485
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High,2025,March,21,Friday,1,480
18,C019,Sara,Farooq,Male,54,Jeddah,Saudi Arabia,2024-03-06,Student,164592.0,781.0,Low,2024,March,6,Wednesday,1,860
19,C020,Noor,Qureshi,Female,33,Mecca,Saudi Arabia,2025-01-21,Student,92730.0,659.0,Medium,2025,January,21,Tuesday,1,539
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914.0,548.0,Low,2025,February,17,Monday,1,512
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High,2025,March,18,Tuesday,1,483
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low,2024,March,26,Tuesday,1,840
30,C031,Unknown,Syed,Female,52,Mecca,Saudi Arabia,2024-03-21,Salaried,173124.0,541.0,Low,2024,March,21,Thursday,1,845
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium,2024,February,21,Wednesday,1,874
35,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low,2024,February,17,Saturday,1,878
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High,2024,March,23,Saturday,1,843
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium,2024,January,22,Monday,1,904
39,C043,Aisha,Ansari,Male,42,Mecca,Saudi Arabia,2025-03-28,Self-Employed,80515.0,621.0,Low,2025,March,28,Friday,1,473
40,C044,Omar,Hussain,Male,31,Dammam,Saudi Arabia,2025-02-04,Self-Employed,105055.0,636.0,Low,2025,February,4,Tuesday,1,525
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium,2025,March,25,Tuesday,1,476
45,C049,Zaid,Ansari,Female,22,Khobar,Saudi Arabia,2024-01-01,Student,91651.0,686.0,Medium,2024,January,1,Monday,1,925
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low,2024,January,24,Wednesday,1,902
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low,2025,February,15,Saturday,1,514
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High,2025,February,14,Friday,1,515
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High,2024,March,11,Monday,1,855
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low,2025,March,14,Friday,1,487
59,C063,Fatima,Shaikh,Female,46,Mecca,Saudi Arabia,2025-01-17,Student,97812.0,749.0,Low,2025,January,17,Friday,1,543
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low,2025,February,3,Monday,1,526
68,C072,Zaid,Ansari,Male,39,Mecca,Saudi Arabia,2025-02-16,Salaried,50766.0,677.0,High,2025,February,16,Sunday,1,513
69,C073,Ahmed,Malik,Male,52,Dammam,Saudi Arabia,2024-01-07,Self-Employed,168503.0,554.0,Medium,2024,January,7,Sunday,1,919
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High,2025,January,10,Friday,1,550
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High,2025,January,23,Thursday,1,537
77,C081,Lina,Shaikh,Female,36,Jeddah,Saudi Arabia,2024-03-02,Student,90484.0,661.0,Low,2024,March,2,Saturday,1,864
85,C089,Sara,Ansari,Male,36,Riyadh,Saudi Arabia,2024-03-21,Salaried,85564.0,782.0,Low,2024,March,21,Thursday,1,845
87,C091,Noor,Farooq,Male,34,Dammam,Saudi Arabia,2025-02-07,Student,91857.0,717.0,Low,2025,February,7,Friday,1,522
88,C092,Maryam,Ansari,Male,37,Jeddah,Saudi Arabia,2024-02-06,Salaried,83495.0,657.0,High,2024,February,6,Tuesday,1,889
90,C094,Maryam,Farooq,Female,25,Mecca,Saudi Arabia,2024-01-21,Self-Employed,124494.0,809.0,Medium,2024,January,21,Sunday,1,905
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486

In [45]:
#Which customers signed up on a Monday?
df[df["signup_weekday"]=="Monday"]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,days_since_signup
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914.0,548.0,Low,2025,February,17,Monday,1,512
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low,2025,April,28,Monday,2,442
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium,2024,January,22,Monday,1,904
45,C049,Zaid,Ansari,Female,22,Khobar,Saudi Arabia,2024-01-01,Student,91651.0,686.0,Medium,2024,January,1,Monday,1,925
46,C050,Sara,Malik,Female,27,Dammam,Saudi Arabia,2024-09-16,Self-Employed,147057.0,667.0,Medium,2024,September,16,Monday,3,666
55,C059,Aisha,Shaikh,Female,60,Jeddah,Saudi Arabia,2024-05-20,Self-Employed,60311.0,646.0,Low,2024,May,20,Monday,2,785
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High,2024,March,11,Monday,1,855
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium,2024,May,13,Monday,2,792
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low,2025,February,3,Monday,1,526
79,C083,Sara,Ansari,Female,34,Dammam,Saudi Arabia,2024-04-01,Self-Employed,43708.0,773.0,Low,2024,April,1,Monday,2,834
80,C084,Noor,Khan,Male,55,Dammam,Saudi Arabia,2024-12-23,Salaried,168680.0,552.0,Low,2024,December,23,Monday,4,568

In [49]:
#How many customers joined each quarter?
df["signup_quarter"].value_counts()

signup_quarter
1    38
2    33
4    15
3    11
Name: count, dtype: int64

In [58]:
#Which month in 2025 had the highest number of signups?
df[df["signup_year"]==2025]["signup_month"].value_counts()

signup_month
February    8
March       8
April       4
January     4
May         2
Name: count, dtype: int64

In [60]:
#Which customers have been with FinPay for more than one year?
df[df["days_since_signup"]>365]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,days_since_signup
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium,2024,October,26,Saturday,4,626
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium,2024,August,20,Tuesday,3,693
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium,2024,July,30,Tuesday,3,714
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium,2024,May,16,Thursday,2,789