In [832]:
#Import Library
import pandas as pd

In [878]:
#Load the customers_dirty.csv dataset into a DataFrame.
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\customers_dirty.csv")

#Display the dataframe
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,NaN,774.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
97,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448,629.0,Medium
98,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173,765.0,Medium
99,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344,647.0,Medium
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307,790.0,High
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073,779.0,Low

In [834]:
#Displays the number of missing values in each column   
df.isnull().sum()

customer_id          0
first_name           1
last_name            0
gender               0
age                  0
city                 0
country              0
signup_date          0
employment_status    1
annual_income        1
credit_score         1
risk_level           0
dtype: int64

In [835]:
#Fill employment status with Unknown
df["employment_status"] = df["employment_status"].fillna("Unknown")

In [836]:
#Fill first name with Unknown
df["first_name"] = df["first_name"].fillna("Unknown")

In [837]:
#Change annual income data type to numeric
df["annual_income"] = pd.to_numeric(df["annual_income"],errors="coerce")

In [838]:
#Fill annual income with median
df["annual_income"] = df["annual_income"].fillna(df["annual_income"].median())

In [839]:
#Counts the number of duplicate rows
df.duplicated().sum()

np.int64(1)

In [840]:
#Displays the duplicates
df[df.duplicated()]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307.0,790.0,High

In [841]:
#Remove duplicates
df = df.drop_duplicates()

In [842]:
#Check the number of duplicate rows 
df.duplicated().sum()

np.int64(0)

In [843]:
#Check duplicate IDs 
df["customer_id"].duplicated().sum()

np.int64(1)

In [844]:
#Display the duplicate rows
df[df["customer_id"].duplicated()]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low

In [845]:
#Check data types
df.dtypes

customer_id              str
first_name               str
last_name                str
gender                   str
age                    int64
city                     str
country                  str
signup_date              str
employment_status        str
annual_income        float64
credit_score         float64
risk_level               str
dtype: object

In [846]:
#Convert signup date
df["signup_date"] = pd.to_datetime(df["signup_date"],errors="coerce")

In [847]:
#Standardize city names
df["city"] = df["city"].str.strip().str.title()

In [848]:
#Standardize employment status
df["employment_status"] = df["employment_status"].str.strip().str.title()

In [849]:
#Standardize gender names
df["gender"] = df["gender"].str.strip().str.title()

In [850]:
#Find invalid ages between 18 min and 100 max
df[~df["age"].between(18,100)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914.0,548.0,Low
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
29,C030,Maryam,Farooq,Male,0,Dammam,Saudi Arabia,2024-04-21,Salaried,55979.0,660.0,Low

In [851]:
#Find invalid credit score between 300 min and 850 max
df[~df["credit_score"].between(300,850)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
10,C011,Fatima,Ansari,Female,45,Khobar,Saudi Arabia,2024-03-14,Self-Employed,76603.0,NaN,High
26,C027,Omar,Hussain,Male,37,Khobar,Saudi Arabia,2024-05-07,Salaried,156164.0,950.0,Low
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low

In [852]:
#Displays customers with negative annual income
df[df["annual_income"]<0]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium

Basic Outlier Detection

In [853]:
#Calculate Q1 and Q3 and IQR
Q1 = df["annual_income"].quantile(0.25)
Q3 = df["annual_income"].quantile(0.75)

IQR = Q3 - Q1

#Lower bound
lower = Q1 - 1.5*IQR 

#Upper bound
upper = Q3 + 1.5*IQR

In [854]:
#Outliers
df[(df["annual_income"]<lower) | (df["annual_income"]>upper)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium

In [855]:
#Check if there are any null values left
df.isnull().sum()

customer_id          0
first_name           0
last_name            0
gender               0
age                  0
city                 0
country              0
signup_date          3
employment_status    0
annual_income        0
credit_score         1
risk_level           0
dtype: int64

In [856]:
#Convert to numeric datatype
df["credit_score"] = pd.to_numeric(df["credit_score"],errors="coerce")

In [857]:
#Remove rows where the signup date is missing
df = df.dropna(subset=["signup_date"])

In [858]:
#Check the signup date still has missing values
df["signup_date"].isnull().sum()

np.int64(0)

In [859]:
#Fill credit score with median
df["credit_score"] = df["credit_score"].fillna(df["credit_score"].median())

In [860]:
#Finally,check if any missing values are still left
df.isnull().sum()

customer_id          0
first_name           0
last_name            0
gender               0
age                  0
city                 0
country              0
signup_date          0
employment_status    0
annual_income        0
credit_score         0
risk_level           0
dtype: int64

In [861]:
#Counts the frequency of each gender value 
df["gender"].value_counts()

gender
Female    50
Male      47
F          1
Name: count, dtype: int64

In [862]:
#Replacing the inconsistent gender value 
df["gender"] = df["gender"].replace({"F":"Female"})

In [863]:
#Counts the frequency of each gender value
df["gender"].value_counts()

gender
Female    51
Male      47
Name: count, dtype: int64

In [864]:
#Replace "-" with "Unknown"
df["employment_status"] = df["employment_status"].replace("-","Unknown")

In [865]:
#Counts the frequency of each employment status 
df["employment_status"].value_counts()

employment_status
Self-Employed    34
Student          32
Salaried         29
Unknown           3
Name: count, dtype: int64

In [866]:
#Counts the number of duplicate customer IDs
df["customer_id"].duplicated().sum()

np.int64(1)

In [867]:
#Counts the number of duplicate customer IDs
df[df["customer_id"].duplicated()]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low

In [868]:
#Display the customer ID duplicate values
df[df["customer_id"].duplicated(keep=False)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
40,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low

In [869]:
#Drop the duplicate the value
df = df.drop(index=101)

In [870]:
#Counts the frequency of each unique value in employment status
df["employment_status"].value_counts()

employment_status
Self-Employed    34
Student          31
Salaried         29
Unknown           3
Name: count, dtype: int64

In [871]:
df["country"].value_counts()

country
Saudi Arabia      96
 Saudi Arabia      1
Name: count, dtype: int64

In [872]:
df["country"] = df["country"].str.strip()

In [ ]:
#f
df[df["city"].str.contains("Riy",case=False,na=False)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
21,C022,Maryam,Ansari,Male,20,Riyadh,Saudi Arabia,2024-12-28,Student,55433.0,617.0,Low
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
34,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
35,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
38,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low
40,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
46,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
52,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
53,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
59,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
61,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
65,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
67,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
75,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
85,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
86,C087,Zaid,Shaikh,Male,35,Riyadh,Saudi Arabia,2024-10-12,Self-Employed,99162.0,767.0,Medium
88,C089,Sara,Ansari,Male,36,Riyadh,Saudi Arabia,2024-03-21,Salaried,85564.0,782.0,Low
96,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
97,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium

In [873]:
#Export the cleaned dataset to an excel file
df.to_excel("customers_clean.xlsx",index=False)

In [874]:
#Export the cleaned dataset to a csv file
df.to_csv("customers_clean.csv",index=False)

Business Questions:

Which columns have missing values?

first name, employment status, annual income, credit score

Which missing values should be filled?

first name, employment status, annual income, credit score

Are customer IDs unique?

No, we have duplicate customer IDs and they should be investigated

Are ages realistic?

Some customer ages fall outside the expected range and require investigation

Are credit scores within an expected range?

Some credit scores are outside the expected range and should be reviewed

Are there inconsistent city or employment or gender values?

Yes, there are inconsistent values in city, employment status and gender.