In [57]:
#Import pandas and numpy 
import pandas as pd

In [ ]:
#Load dataset 
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\pandas\customer_dates.csv")

In [ ]:
#Displays the dataframe
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,days_since_signup
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium,2024,October,26,Saturday,4,626
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium,2024,August,20,Tuesday,3,693
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium,2024,July,30,Tuesday,3,714
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium,2024,May,16,Thursday,2,789

In [34]:
#creates a new column showing each customer's estimated monthly income
df["monthly_income"] = df["annual_income"]/12

In [ ]:
#Clarifies customers as high value based on whether their annual income exceeds 100,000
df["high_value_customer"] = np.where(df["annual_income"]>100000,"Yes","No")

In [ ]:
#Converts annual income into thousands for easier reporting
df["annual_income_k"] = df["annual_income"].apply(lambda x:round(x/1000,1))

In [ ]:
#Maps each risk level to a numerical score for easier analysis
df["risk_score"] = df["risk_level"].map({"Low":1,"Medium":2,"High":3})

In [ ]:
#Groups customers in age categories
def age_group(age):
    if age < 25:
        return "Young Adult"
    elif age < 40:
        return "Adult"
    elif age < 60:
        return "Middle Aged"
    else:
        return "Senior"

In [17]:
df["age_group"] = df["age"].apply(age_group)

In [ ]:
#Categorizes customers into income bands
def income_band(income):
    if income < 50000:
        return "Low"
    elif income < 100000:
        return "Medium"
    else:
        return "High"

In [18]:
df["income_band"] = df["annual_income"].apply(income_band)

In [ ]:
#Categorizes customers based on their credit score 
def credit_category(score):
    if score >= 750:
        return "Excellent"
    
    elif score >=650:
        return "Good"

    elif score >= 550:
        return "Fair"

    else:
        return "Poor"

In [23]:
df["credit_score_category"] = df["credit_score"].apply(credit_category)

In [ ]:
#Renames the tenure column to improve readability
df.rename(columns={
    "days_since_signup":"customer_tenure_days"
},inplace=True)

In [ ]:
#Identifies customers with both high income and excellent credit
df["high_value_customer"] = np.where(
    (df["annual_income"]>100000) & (df["credit_score"]>750),"Yes","No"
)

In [ ]:
#Converts risk level into business friendly risk segments
df["risk_segment"] = df["risk_level"].map({"Low":"Safe","Medium":"Monitor","High":"High Risk"})

In [35]:
#Which age group has the most of the customers?
df["age_group"].value_counts()

age_group
Middle Aged    45
Adult          40
Young Adult     8
Senior          4
Name: count, dtype: int64

In [37]:
#How many high value customers do we have?
df["high_value_customer"].value_counts()

high_value_customer
No     81
Yes    16
Name: count, dtype: int64

In [ ]:
#Which income band has the most customers?
df["income_band"].value_counts()

income_band
High      51
Medium    40
Low        6
Name: count, dtype: int64

In [ ]:
#Which credit score category is most common?
df["credit_score_category"].value_counts()

credit_score_category
Excellent    36
Good         24
Fair         24
Poor         13
Name: count, dtype: int64

In [48]:
#Average income by age group
df.groupby("age_group")["annual_income"].mean().sort_values(ascending=False)

age_group
Middle Aged    110906.433333
Adult          110038.987500
Senior          90185.500000
Young Adult     87638.750000
Name: annual_income, dtype: float64

In [47]:
#Average credit score by income band 
df.groupby("income_band")["credit_score"].mean().sort_values(ascending=False)

income_band
Low       712.833333
Medium    704.225000
High      673.000000
Name: credit_score, dtype: float64

In [55]:
pd.set_option("display.max_columns",None)
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854,5572.333333,No,66.9,3,Adult,Medium,Excellent,High Risk
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878,8415.833333,Yes,101.0,3,Young Adult,High,Excellent,High Risk
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813,9410.500000,No,112.9,1,Middle Aged,High,Poor,Safe
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435,5566.083333,No,66.8,2,Adult,Medium,Poor,Monitor
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512,8505.541667,Yes,102.1,1,Middle Aged,High,Excellent,Safe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium,2024,October,26,Saturday,4,626,14075.166667,No,168.9,2,Adult,High,Poor,Monitor
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486,10538.000000,No,126.5,3,Middle Aged,High,Good,High Risk
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium,2024,August,20,Tuesday,3,693,10204.000000,No,122.4,2,Middle Aged,High,Fair,Monitor
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium,2024,July,30,Tuesday,3,714,7431.083333,No,89.2,2,Middle Aged,Medium,Excellent,Monitor
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium,2024,May,16,Thursday,2,789,6195.333333,No,74.3,2,Young Adult,Medium,Fair,Monitor

In [56]:
df.to_csv("customers_features.csv",index=False)