In [109]:
#Import library
import pandas as pd

In [ ]:
#Load the dataset
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\pandas\customers_clean.csv")

In [68]:
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium

In [69]:
#Select one column 
df["city"]

0     Jeddah
1     Riyadh
2     Khobar
3     Jeddah
4     Dammam
       ...
92    Jeddah
93    Riyadh
94    Riyadh
95    Khobar
96    Jeddah
Name: city, Length: 97, dtype: str

In [ ]:
#Select multiple column
df[["first_name","city"]]

   first_name    city
0        Sara  Jeddah
1      Maryam  Riyadh
2         Ali  Khobar
3       Ahmed  Jeddah
4        Sara  Dammam
..        ...     ...
92       Omar  Jeddah
93     Fatima  Riyadh
94       Lina  Riyadh
95       Sara  Khobar
96       Zaid  Jeddah

[97 rows x 2 columns]

In [ ]:
#Select specific rows and columns
df.loc[0:5]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low

In [ ]:
#Select rows using iloc
df.iloc[0:5]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low

In [ ]:
#Select specific rows and columns
df.loc[0:5,["first_name","city"]]

  first_name    city
0       Sara  Jeddah
1     Maryam  Riyadh
2        Ali  Khobar
3      Ahmed  Jeddah
4       Sara  Dammam
5      Ahmed   Mecca

In [ ]:
#Boolean mask
df[df["age"]>30]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium

In [75]:
#Multiple Conditions
df[(df["age"]>30) & (df["city"]=="Riyadh")]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
35,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
72,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
82,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
83,C087,Zaid,Shaikh,Male,35,Riyadh,Saudi Arabia,2024-10-12,Self-Employed,99162.0,767.0,Medium
85,C089,Sara,Ansari,Male,36,Riyadh,Saudi Arabia,2024-03-21,Salaried,85564.0,782.0,Low
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium

In [76]:
#OR condition
df[(df["city"]=="Riyadh") | (df["city"]=="Jeddah")]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
16,C017,Zaid,Ansari,Male,43,Jeddah,Saudi Arabia,2024-10-03,Student,40149.0,806.0,Medium
18,C019,Sara,Farooq,Male,54,Jeddah,Saudi Arabia,2024-03-06,Student,164592.0,781.0,Low
20,C021,Fatima,Farooq,Male,27,Jeddah,Saudi Arabia,2024-04-25,Salaried,128627.0,510.0,High
21,C022,Maryam,Ansari,Male,20,Riyadh,Saudi Arabia,2024-12-28,Student,55433.0,617.0,Low
22,C023,Ali,Malik,Female,52,Jeddah,Saudi Arabia,2024-05-22,Student,167248.0,609.0,High
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
35,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium
41,C045,Sara,Hussain,Male,50,Jeddah,Saudi Arabia,2024-04-12,Self-Employed,131660.0,656.0,Low
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
49,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
55,C059,Aisha,Shaikh,Female,60,Jeddah,Saudi Arabia,2024-05-20,Self-Employed,60311.0,646.0,Low
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
65,C069,Aisha,Khan,Male,35,Jeddah,Saudi Arabia,2024-08-30,Student,69986.0,788.0,Low
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
72,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
77,C081,Lina,Shaikh,Female,36,Jeddah,Saudi Arabia,2024-03-02,Student,90484.0,661.0,Low
82,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
83,C087,Zaid,Shaikh,Male,35,Riyadh,Saudi Arabia,2024-10-12,Self-Employed,99162.0,767.0,Medium
85,C089,Sara,Ansari,Male,36,Riyadh,Saudi Arabia,2024-03-21,Salaried,85564.0,782.0,Low
88,C092,Maryam,Ansari,Male,37,Jeddah,Saudi Arabia,2024-02-06,Salaried,83495.0,657.0,High
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium

In [ ]:
#Using query()
df.query("age > 60")

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High

In [ ]:
#Sort data
df.sort_values("annual_income")

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
16,C017,Zaid,Ansari,Male,43,Jeddah,Saudi Arabia,2024-10-03,Student,40149.0,806.0,Medium
73,C077,Fatima,Shaikh,Female,37,Mecca,Saudi Arabia,2024-12-25,Self-Employed,42661.0,764.0,Low
79,C083,Sara,Ansari,Female,34,Dammam,Saudi Arabia,2024-04-01,Self-Employed,43708.0,773.0,Low
61,C065,Omar,Syed,Male,45,Mecca,Saudi Arabia,2024-10-15,Student,47104.0,542.0,High
...,...,...,...,...,...,...,...,...,...,...,...,...
44,C048,Ali,Iqbal,Female,42,Dammam,Saudi Arabia,2024-08-11,Student,174066.0,559.0,Medium
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
78,C082,Maryam,Rahman,Male,33,Khobar,Saudi Arabia,2024-05-21,Student,177530.0,805.0,Medium
13,C014,Ahmed,Syed,Male,44,Khobar,Saudi Arabia,2024-11-01,Self-Employed,178704.0,628.0,High
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High

In [ ]:
#Sort descending
df.sort_values("annual_income",ascending=False)

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
13,C014,Ahmed,Syed,Male,44,Khobar,Saudi Arabia,2024-11-01,Self-Employed,178704.0,628.0,High
78,C082,Maryam,Rahman,Male,33,Khobar,Saudi Arabia,2024-05-21,Student,177530.0,805.0,Medium
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
44,C048,Ali,Iqbal,Female,42,Dammam,Saudi Arabia,2024-08-11,Student,174066.0,559.0,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
61,C065,Omar,Syed,Male,45,Mecca,Saudi Arabia,2024-10-15,Student,47104.0,542.0,High
79,C083,Sara,Ansari,Female,34,Dammam,Saudi Arabia,2024-04-01,Self-Employed,43708.0,773.0,Low
73,C077,Fatima,Shaikh,Female,37,Mecca,Saudi Arabia,2024-12-25,Self-Employed,42661.0,764.0,Low
16,C017,Zaid,Ansari,Male,43,Jeddah,Saudi Arabia,2024-10-03,Student,40149.0,806.0,Medium
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium

In [ ]:
#Count values
df["city"].value_counts()

city
Riyadh    25
Khobar    21
Jeddah    18
Dammam    18
Mecca     15
Name: count, dtype: int64

In [81]:
#Show customers from Riyadh.
df[df["city"]=="Riyadh"]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
21,C022,Maryam,Ansari,Male,20,Riyadh,Saudi Arabia,2024-12-28,Student,55433.0,617.0,Low
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
35,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
49,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
72,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
82,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
83,C087,Zaid,Shaikh,Male,35,Riyadh,Saudi Arabia,2024-10-12,Self-Employed,99162.0,767.0,Medium
85,C089,Sara,Ansari,Male,36,Riyadh,Saudi Arabia,2024-03-21,Salaried,85564.0,782.0,Low
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium

In [82]:
#Find customers older than 40
df[df["age"]>40]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low
10,C011,Fatima,Ansari,Female,45,Khobar,Saudi Arabia,2024-03-14,Self-Employed,76603.0,686.0,High
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low
13,C014,Ahmed,Syed,Male,44,Khobar,Saudi Arabia,2024-11-01,Self-Employed,178704.0,628.0,High
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
16,C017,Zaid,Ansari,Male,43,Jeddah,Saudi Arabia,2024-10-03,Student,40149.0,806.0,Medium
17,C018,Lina,Khan,Male,43,Dammam,Saudi Arabia,2024-05-02,Salaried,103143.0,790.0,Low
18,C019,Sara,Farooq,Male,54,Jeddah,Saudi Arabia,2024-03-06,Student,164592.0,781.0,Low
22,C023,Ali,Malik,Female,52,Jeddah,Saudi Arabia,2024-05-22,Student,167248.0,609.0,High
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
30,C031,Unknown,Syed,Female,52,Mecca,Saudi Arabia,2024-03-21,Salaried,173124.0,541.0,Low
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
33,C037,Noor,Syed,Male,55,Dammam,Saudi Arabia,2025-04-22,Unknown,67154.0,568.0,Medium
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium
39,C043,Aisha,Ansari,Male,42,Mecca,Saudi Arabia,2025-03-28,Self-Employed,80515.0,621.0,Low
41,C045,Sara,Hussain,Male,50,Jeddah,Saudi Arabia,2024-04-12,Self-Employed,131660.0,656.0,Low
42,C046,Aisha,Khan,Male,45,Dammam,Saudi Arabia,2024-05-22,Salaried,113170.0,679.0,High
44,C048,Ali,Iqbal,Female,42,Dammam,Saudi Arabia,2024-08-11,Student,174066.0,559.0,Medium
51,C055,Lina,Hussain,Male,44,Khobar,Saudi Arabia,2024-07-23,Salaried,78684.0,835.0,High
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
54,C058,Fatima,Farooq,Female,55,Khobar,Saudi Arabia,2025-04-04,Salaried,164433.0,730.0,Medium
55,C059,Aisha,Shaikh,Female,60,Jeddah,Saudi Arabia,2024-05-20,Self-Employed,60311.0,646.0,Low
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
57,C061,Omar,Ansari,Male,46,Khobar,Saudi Arabia,2024-06-18,Student,162139.0,712.0,Low
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
59,C063,Fatima,Shaikh,Female,46,Mecca,Saudi Arabia,2025-01-17,Student,97812.0,749.0,Low
61,C065,Omar,Syed,Male,45,Mecca,Saudi Arabia,2024-10-15,Student,47104.0,542.0,High
69,C073,Ahmed,Malik,Male,52,Dammam,Saudi Arabia,2024-01-07,Self-Employed,168503.0,554.0,Medium
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
71,C075,Lina,Farooq,Female,57,Dammam,Saudi Arabia,2024-06-14,Salaried,62718.0,642.0,Medium
72,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High
76,C080,Zaid,Malik,Female,55,Mecca,Saudi Arabia,2024-06-25,Self-Employed,126714.0,680.0,High
80,C084,Noor,Khan,Male,55,Dammam,Saudi Arabia,2024-12-23,Salaried,168680.0,552.0,Low
81,C085,Zaid,Shaikh,Female,50,Khobar,Saudi Arabia,2024-06-23,Salaried,53468.0,629.0,Medium
82,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
84,C088,Lina,Farooq,Female,57,Khobar,Saudi Arabia,2024-06-05,Student,55789.0,812.0,High
86,C090,Omar,Khan,Female,48,Mecca,Saudi Arabia,2024-08-28,Self-Employed,48556.0,618.0,Medium
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium

In [83]:
#List all high-risk customers.
df[df["risk_level"]=="High"]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
7,C008,Omar,Malik,Female,33,Dammam,Saudi Arabia,2024-12-25,Student,58717.0,811.0,High
9,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307.0,790.0,High
10,C011,Fatima,Ansari,Female,45,Khobar,Saudi Arabia,2024-03-14,Self-Employed,76603.0,686.0,High
13,C014,Ahmed,Syed,Male,44,Khobar,Saudi Arabia,2024-11-01,Self-Employed,178704.0,628.0,High
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
20,C021,Fatima,Farooq,Male,27,Jeddah,Saudi Arabia,2024-04-25,Salaried,128627.0,510.0,High
22,C023,Ali,Malik,Female,52,Jeddah,Saudi Arabia,2024-05-22,Student,167248.0,609.0,High
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
34,C038,Sara,Iqbal,Male,37,Dammam,Saudi Arabia,2024-11-05,Unknown,129884.0,604.0,High
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High
42,C046,Aisha,Khan,Male,45,Dammam,Saudi Arabia,2024-05-22,Salaried,113170.0,679.0,High
47,C051,Noor,Qureshi,Male,32,Khobar,Saudi Arabia,2024-12-06,Self-Employed,85620.0,815.0,High
51,C055,Lina,Hussain,Male,44,Khobar,Saudi Arabia,2024-07-23,Salaried,78684.0,835.0,High
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
61,C065,Omar,Syed,Male,45,Mecca,Saudi Arabia,2024-10-15,Student,47104.0,542.0,High
63,C067,Fatima,Malik,Female,37,Khobar,Saudi Arabia,2024-05-09,Salaried,163288.0,509.0,High
68,C072,Zaid,Ansari,Male,39,Mecca,Saudi Arabia,2025-02-16,Salaried,50766.0,677.0,High
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High
75,C079,Lina,Farooq,Male,25,Dammam,Saudi Arabia,2024-04-23,Self-Employed,103780.0,656.0,High
76,C080,Zaid,Malik,Female,55,Mecca,Saudi Arabia,2024-06-25,Self-Employed,126714.0,680.0,High
84,C088,Lina,Farooq,Female,57,Khobar,Saudi Arabia,2024-06-05,Student,55789.0,812.0,High
88,C092,Maryam,Ansari,Male,37,Jeddah,Saudi Arabia,2024-02-06,Salaried,83495.0,657.0,High
89,C093,Zaid,Shaikh,Female,27,Khobar,Saudi Arabia,2024-12-18,Self-Employed,145515.0,639.0,High
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High

In [84]:
#Which customers earn above the average annual income?
average_income = df["annual_income"].mean()
df[df["annual_income"]>average_income]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low
13,C014,Ahmed,Syed,Male,44,Khobar,Saudi Arabia,2024-11-01,Self-Employed,178704.0,628.0,High
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
18,C019,Sara,Farooq,Male,54,Jeddah,Saudi Arabia,2024-03-06,Student,164592.0,781.0,Low
20,C021,Fatima,Farooq,Male,27,Jeddah,Saudi Arabia,2024-04-25,Salaried,128627.0,510.0,High
22,C023,Ali,Malik,Female,52,Jeddah,Saudi Arabia,2024-05-22,Student,167248.0,609.0,High
26,C027,Omar,Hussain,Male,37,Khobar,Saudi Arabia,2024-05-07,Salaried,156164.0,950.0,Low
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
30,C031,Unknown,Syed,Female,52,Mecca,Saudi Arabia,2024-03-21,Salaried,173124.0,541.0,Low
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
34,C038,Sara,Iqbal,Male,37,Dammam,Saudi Arabia,2024-11-05,Unknown,129884.0,604.0,High
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium
41,C045,Sara,Hussain,Male,50,Jeddah,Saudi Arabia,2024-04-12,Self-Employed,131660.0,656.0,Low
42,C046,Aisha,Khan,Male,45,Dammam,Saudi Arabia,2024-05-22,Salaried,113170.0,679.0,High
44,C048,Ali,Iqbal,Female,42,Dammam,Saudi Arabia,2024-08-11,Student,174066.0,559.0,Medium
46,C050,Sara,Malik,Female,27,Dammam,Saudi Arabia,2024-09-16,Self-Employed,147057.0,667.0,Medium
48,C052,Noor,Hussain,Male,39,Dammam,Saudi Arabia,2024-04-17,Self-Employed,124475.0,738.0,Medium
49,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
54,C058,Fatima,Farooq,Female,55,Khobar,Saudi Arabia,2025-04-04,Salaried,164433.0,730.0,Medium
57,C061,Omar,Ansari,Male,46,Khobar,Saudi Arabia,2024-06-18,Student,162139.0,712.0,Low
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
60,C064,Noor,Hussain,Female,21,Khobar,Saudi Arabia,2024-06-21,Student,145989.0,584.0,Medium
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
63,C067,Fatima,Malik,Female,37,Khobar,Saudi Arabia,2024-05-09,Salaried,163288.0,509.0,High
67,C071,Sara,Syed,Male,39,Mecca,Saudi Arabia,2024-12-12,Self-Employed,143980.0,601.0,Low
69,C073,Ahmed,Malik,Male,52,Dammam,Saudi Arabia,2024-01-07,Self-Employed,168503.0,554.0,Medium
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High
76,C080,Zaid,Malik,Female,55,Mecca,Saudi Arabia,2024-06-25,Self-Employed,126714.0,680.0,High
78,C082,Maryam,Rahman,Male,33,Khobar,Saudi Arabia,2024-05-21,Student,177530.0,805.0,Medium
80,C084,Noor,Khan,Male,55,Dammam,Saudi Arabia,2024-12-23,Salaried,168680.0,552.0,Low
89,C093,Zaid,Shaikh,Female,27,Khobar,Saudi Arabia,2024-12-18,Self-Employed,145515.0,639.0,High
90,C094,Maryam,Farooq,Female,25,Mecca,Saudi Arabia,2024-01-21,Self-Employed,124494.0,809.0,Medium
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        97 non-null     str
 1   first_name         97 non-null     str
 2   last_name          97 non-null     str
 3   gender             97 non-null     str
 4   age                97 non-null     int64
 5   city               97 non-null     str
 6   country            97 non-null     str
 7   signup_date        97 non-null     str
 8   employment_status  97 non-null     str
 9   annual_income      97 non-null     float64
 10  credit_score       97 non-null     float64
 11  risk_level         97 non-null     str
dtypes: float64(2), int64(1), str(9)
memory usage: 9.2 KB

In [ ]:
#Convert the sign up date to datetime
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [87]:
#Which customers signed up in 2025?
df[df["signup_date"].dt.year==2025]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
19,C020,Noor,Qureshi,Female,33,Mecca,Saudi Arabia,2025-01-21,Student,92730.0,659.0,Medium
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914.0,548.0,Low
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
33,C037,Noor,Syed,Male,55,Dammam,Saudi Arabia,2025-04-22,Unknown,67154.0,568.0,Medium
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
39,C043,Aisha,Ansari,Male,42,Mecca,Saudi Arabia,2025-03-28,Self-Employed,80515.0,621.0,Low
40,C044,Omar,Hussain,Male,31,Dammam,Saudi Arabia,2025-02-04,Self-Employed,105055.0,636.0,Low
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
54,C058,Fatima,Farooq,Female,55,Khobar,Saudi Arabia,2025-04-04,Salaried,164433.0,730.0,Medium
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
59,C063,Fatima,Shaikh,Female,46,Mecca,Saudi Arabia,2025-01-17,Student,97812.0,749.0,Low
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
68,C072,Zaid,Ansari,Male,39,Mecca,Saudi Arabia,2025-02-16,Salaried,50766.0,677.0,High
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High
87,C091,Noor,Farooq,Male,34,Dammam,Saudi Arabia,2025-02-07,Student,91857.0,717.0,Low
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High

In [88]:
#Which cities have the most customers?
df["city"].value_counts()

city
Riyadh    25
Khobar    21
Jeddah    18
Dammam    18
Mecca     15
Name: count, dtype: int64

In [89]:
#Show customers who are students
df[df["employment_status"]=="Student"]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
7,C008,Omar,Malik,Female,33,Dammam,Saudi Arabia,2024-12-25,Student,58717.0,811.0,High
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low
16,C017,Zaid,Ansari,Male,43,Jeddah,Saudi Arabia,2024-10-03,Student,40149.0,806.0,Medium
18,C019,Sara,Farooq,Male,54,Jeddah,Saudi Arabia,2024-03-06,Student,164592.0,781.0,Low
19,C020,Noor,Qureshi,Female,33,Mecca,Saudi Arabia,2025-01-21,Student,92730.0,659.0,Medium
21,C022,Maryam,Ansari,Male,20,Riyadh,Saudi Arabia,2024-12-28,Student,55433.0,617.0,Low
22,C023,Ali,Malik,Female,52,Jeddah,Saudi Arabia,2024-05-22,Student,167248.0,609.0,High
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
35,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
44,C048,Ali,Iqbal,Female,42,Dammam,Saudi Arabia,2024-08-11,Student,174066.0,559.0,Medium
45,C049,Zaid,Ansari,Female,22,Khobar,Saudi Arabia,2024-01-01,Student,91651.0,686.0,Medium
49,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
57,C061,Omar,Ansari,Male,46,Khobar,Saudi Arabia,2024-06-18,Student,162139.0,712.0,Low
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
59,C063,Fatima,Shaikh,Female,46,Mecca,Saudi Arabia,2025-01-17,Student,97812.0,749.0,Low
60,C064,Noor,Hussain,Female,21,Khobar,Saudi Arabia,2024-06-21,Student,145989.0,584.0,Medium
61,C065,Omar,Syed,Male,45,Mecca,Saudi Arabia,2024-10-15,Student,47104.0,542.0,High
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
65,C069,Aisha,Khan,Male,35,Jeddah,Saudi Arabia,2024-08-30,Student,69986.0,788.0,Low
66,C070,Lina,Shaikh,Female,30,Mecca,Saudi Arabia,2024-11-06,Student,70024.0,583.0,Medium
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
77,C081,Lina,Shaikh,Female,36,Jeddah,Saudi Arabia,2024-03-02,Student,90484.0,661.0,Low
78,C082,Maryam,Rahman,Male,33,Khobar,Saudi Arabia,2024-05-21,Student,177530.0,805.0,Medium
82,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
84,C088,Lina,Farooq,Female,57,Khobar,Saudi Arabia,2024-06-05,Student,55789.0,812.0,High
87,C091,Noor,Farooq,Male,34,Dammam,Saudi Arabia,2025-02-07,Student,91857.0,717.0,Low
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium

In [90]:
#Show female customers from Riyadh
df[(df["gender"]=="Female") & (df["city"]=="Riyadh")]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
35,C039,Noor,Qureshi,Female,36,Riyadh,Saudi Arabia,2024-02-17,Student,102066.5,641.0,Low
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
49,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
72,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
82,C086,Sara,Iqbal,Female,51,Riyadh,Saudi Arabia,2024-10-22,Student,54053.0,577.0,Low
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium

In [91]:
#Show salaried customers earning more than 100,000
df[(df["employment_status"] == "Salaried") & (df["annual_income"]>100000)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
17,C018,Lina,Khan,Male,43,Dammam,Saudi Arabia,2024-05-02,Salaried,103143.0,790.0,Low
20,C021,Fatima,Farooq,Male,27,Jeddah,Saudi Arabia,2024-04-25,Salaried,128627.0,510.0,High
26,C027,Omar,Hussain,Male,37,Khobar,Saudi Arabia,2024-05-07,Salaried,156164.0,950.0,Low
30,C031,Unknown,Syed,Female,52,Mecca,Saudi Arabia,2024-03-21,Salaried,173124.0,541.0,Low
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
42,C046,Aisha,Khan,Male,45,Dammam,Saudi Arabia,2024-05-22,Salaried,113170.0,679.0,High
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
54,C058,Fatima,Farooq,Female,55,Khobar,Saudi Arabia,2025-04-04,Salaried,164433.0,730.0,Medium
56,C060,Noor,Malik,Female,54,Riyadh,Saudi Arabia,2024-03-11,Salaried,100623.0,696.0,High
63,C067,Fatima,Malik,Female,37,Khobar,Saudi Arabia,2024-05-09,Salaried,163288.0,509.0,High
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High
80,C084,Noor,Khan,Male,55,Dammam,Saudi Arabia,2024-12-23,Salaried,168680.0,552.0,Low
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium

In [92]:
#Find customers with a credit score above 750.
df[df["credit_score"]>750]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
7,C008,Omar,Malik,Female,33,Dammam,Saudi Arabia,2024-12-25,Student,58717.0,811.0,High
8,C009,Omar,Qureshi,Male,30,Khobar,Saudi Arabia,2024-07-13,Self-Employed,97570.0,850.0,Medium
9,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307.0,790.0,High
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
15,C016,Noor,Qureshi,Male,52,Riyadh,Saudi Arabia,2025-03-21,Unknown,118235.0,827.0,High
16,C017,Zaid,Ansari,Male,43,Jeddah,Saudi Arabia,2024-10-03,Student,40149.0,806.0,Medium
17,C018,Lina,Khan,Male,43,Dammam,Saudi Arabia,2024-05-02,Salaried,103143.0,790.0,Low
18,C019,Sara,Farooq,Male,54,Jeddah,Saudi Arabia,2024-03-06,Student,164592.0,781.0,Low
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium
26,C027,Omar,Hussain,Male,37,Khobar,Saudi Arabia,2024-05-07,Salaried,156164.0,950.0,Low
31,C035,Sara,Khan,Female,59,Riyadh,Saudi Arabia,2024-02-21,Salaried,95877.0,759.0,Medium
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
47,C051,Noor,Qureshi,Male,32,Khobar,Saudi Arabia,2024-12-06,Self-Employed,85620.0,815.0,High
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
51,C055,Lina,Hussain,Male,44,Khobar,Saudi Arabia,2024-07-23,Salaried,78684.0,835.0,High
53,C057,Maryam,Ansari,Male,49,Jeddah,Saudi Arabia,2025-02-14,Self-Employed,179233.0,786.0,High
65,C069,Aisha,Khan,Male,35,Jeddah,Saudi Arabia,2024-08-30,Student,69986.0,788.0,Low
70,C074,Fatima,Farooq,Male,47,Jeddah,Saudi Arabia,2025-01-10,Student,110800.0,815.0,High
73,C077,Fatima,Shaikh,Female,37,Mecca,Saudi Arabia,2024-12-25,Self-Employed,42661.0,764.0,Low
74,C078,Sara,Ansari,Female,51,Mecca,Saudi Arabia,2025-01-23,Salaried,164804.0,830.0,High
78,C082,Maryam,Rahman,Male,33,Khobar,Saudi Arabia,2024-05-21,Student,177530.0,805.0,Medium
79,C083,Sara,Ansari,Female,34,Dammam,Saudi Arabia,2024-04-01,Self-Employed,43708.0,773.0,Low
83,C087,Zaid,Shaikh,Male,35,Riyadh,Saudi Arabia,2024-10-12,Self-Employed,99162.0,767.0,Medium
84,C088,Lina,Farooq,Female,57,Khobar,Saudi Arabia,2024-06-05,Student,55789.0,812.0,High
85,C089,Sara,Ansari,Male,36,Riyadh,Saudi Arabia,2024-03-21,Salaried,85564.0,782.0,Low
90,C094,Maryam,Farooq,Female,25,Mecca,Saudi Arabia,2024-01-21,Self-Employed,124494.0,809.0,Medium
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium

In [93]:
#Which customers have both a high risk level and a credit score below 600
df[(df["risk_level"]=="High") & (df["credit_score"]<600)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
20,C021,Fatima,Farooq,Male,27,Jeddah,Saudi Arabia,2024-04-25,Salaried,128627.0,510.0,High
61,C065,Omar,Syed,Male,45,Mecca,Saudi Arabia,2024-10-15,Student,47104.0,542.0,High
63,C067,Fatima,Malik,Female,37,Khobar,Saudi Arabia,2024-05-09,Salaried,163288.0,509.0,High

In [94]:
#Show customers between ages 25 and 35.
df[df["age"].between(25,35)]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
7,C008,Omar,Malik,Female,33,Dammam,Saudi Arabia,2024-12-25,Student,58717.0,811.0,High
8,C009,Omar,Qureshi,Male,30,Khobar,Saudi Arabia,2024-07-13,Self-Employed,97570.0,850.0,Medium
12,C013,Omar,Qureshi,Female,25,Riyadh,Saudi Arabia,2025-03-16,Salaried,80066.0,821.0,Low
19,C020,Noor,Qureshi,Female,33,Mecca,Saudi Arabia,2025-01-21,Student,92730.0,659.0,Medium
20,C021,Fatima,Farooq,Male,27,Jeddah,Saudi Arabia,2024-04-25,Salaried,128627.0,510.0,High
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low
32,C036,Omar,Malik,Male,35,Riyadh,Saudi Arabia,2024-05-25,Salaried,154867.0,778.0,High
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
40,C044,Omar,Hussain,Male,31,Dammam,Saudi Arabia,2025-02-04,Self-Employed,105055.0,636.0,Low
46,C050,Sara,Malik,Female,27,Dammam,Saudi Arabia,2024-09-16,Self-Employed,147057.0,667.0,Medium
47,C051,Noor,Qureshi,Male,32,Khobar,Saudi Arabia,2024-12-06,Self-Employed,85620.0,815.0,High
49,C053,Lina,Ansari,Female,30,Riyadh,Saudi Arabia,2024-05-25,Student,127867.0,547.0,Low
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
64,C068,Maryam,Khan,Female,34,Riyadh,Saudi Arabia,2025-02-03,Student,50553.0,515.0,Low
65,C069,Aisha,Khan,Male,35,Jeddah,Saudi Arabia,2024-08-30,Student,69986.0,788.0,Low
66,C070,Lina,Shaikh,Female,30,Mecca,Saudi Arabia,2024-11-06,Student,70024.0,583.0,Medium
75,C079,Lina,Farooq,Male,25,Dammam,Saudi Arabia,2024-04-23,Self-Employed,103780.0,656.0,High
78,C082,Maryam,Rahman,Male,33,Khobar,Saudi Arabia,2024-05-21,Student,177530.0,805.0,Medium
79,C083,Sara,Ansari,Female,34,Dammam,Saudi Arabia,2024-04-01,Self-Employed,43708.0,773.0,Low
83,C087,Zaid,Shaikh,Male,35,Riyadh,Saudi Arabia,2024-10-12,Self-Employed,99162.0,767.0,Medium
87,C091,Noor,Farooq,Male,34,Dammam,Saudi Arabia,2025-02-07,Student,91857.0,717.0,Low
89,C093,Zaid,Shaikh,Female,27,Khobar,Saudi Arabia,2024-12-18,Self-Employed,145515.0,639.0,High
90,C094,Maryam,Farooq,Female,25,Mecca,Saudi Arabia,2024-01-21,Self-Employed,124494.0,809.0,Medium

In [95]:
#Which city has the highest average annual income?
df.groupby("city")["annual_income"].mean().sort_values(ascending=False)

city
Jeddah    115676.055556
Khobar    115207.952381
Dammam    109768.694444
Riyadh    100499.500000
Mecca      97622.733333
Name: annual_income, dtype: float64

In [96]:
#Which employment status has the highest number of customers?
df["employment_status"].value_counts()

employment_status
Self-Employed    34
Student          31
Salaried         29
Unknown           3
Name: count, dtype: int64

In [97]:
#Display the top 10 highest-income customers?
df["annual_income"].sort_values(ascending=False).head(10)

53    179233.0
13    178704.0
78    177530.0
52    175779.0
44    174066.0
30    173124.0
92    168902.0
80    168680.0
69    168503.0
27    167307.0
Name: annual_income, dtype: float64

In [98]:
#Show customers sorted by signup date (newest first)?
df.sort_values("signup_date",ascending=False)

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
33,C037,Noor,Syed,Male,55,Dammam,Saudi Arabia,2025-04-22,Unknown,67154.0,568.0,Medium
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium
90,C094,Maryam,Farooq,Female,25,Mecca,Saudi Arabia,2024-01-21,Self-Employed,124494.0,809.0,Medium
69,C073,Ahmed,Malik,Male,52,Dammam,Saudi Arabia,2024-01-07,Self-Employed,168503.0,554.0,Medium
45,C049,Zaid,Ansari,Female,22,Khobar,Saudi Arabia,2024-01-01,Student,91651.0,686.0,Medium

In [ ]:
#Show customers sorted by signup date (newest first)
df.sort_values("signup_date",ascending=False)

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
33,C037,Noor,Syed,Male,55,Dammam,Saudi Arabia,2025-04-22,Unknown,67154.0,568.0,Medium
11,C012,Maryam,Qureshi,Female,57,Khobar,Saudi Arabia,2025-04-04,Student,144700.0,685.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
50,C054,Noor,Ansari,Male,29,Riyadh,Saudi Arabia,2024-01-24,Salaried,164554.0,812.0,Low
38,C042,Fatima,Syed,Male,47,Jeddah,Saudi Arabia,2024-01-22,Self-Employed,135591.0,520.0,Medium
90,C094,Maryam,Farooq,Female,25,Mecca,Saudi Arabia,2024-01-21,Self-Employed,124494.0,809.0,Medium
69,C073,Ahmed,Malik,Male,52,Dammam,Saudi Arabia,2024-01-07,Self-Employed,168503.0,554.0,Medium
45,C049,Zaid,Ansari,Female,22,Khobar,Saudi Arabia,2024-01-01,Student,91651.0,686.0,Medium

In [ ]:
#Which country has the most customers?
df["country"].value_counts()

country
Saudi Arabia    97
Name: count, dtype: int64

In [ ]:
#Show customers whose first name starts with the letter "A".
df[df["first_name"].str.startswith("A")]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
5,C006,Ahmed,Iqbal,Female,60,Mecca,Saudi Arabia,2025-03-29,Self-Employed,90407.0,535.0,Low
6,C007,Aisha,Shaikh,Male,34,Riyadh,Saudi Arabia,2024-07-13,Self-Employed,158858.0,825.0,Medium
9,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307.0,790.0,High
13,C014,Ahmed,Syed,Male,44,Khobar,Saudi Arabia,2024-11-01,Self-Employed,178704.0,628.0,High
14,C015,Ali,Iqbal,Female,41,Riyadh,Saudi Arabia,2024-05-30,Self-Employed,81460.0,732.0,Low
22,C023,Ali,Malik,Female,52,Jeddah,Saudi Arabia,2024-05-22,Student,167248.0,609.0,High
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200.0,844.0,High
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low
28,C029,Ahmed,Khan,Male,44,Riyadh,Saudi Arabia,2024-07-18,Self-Employed,159277.0,646.0,Medium
36,C040,Ali,Malik,Male,60,Dammam,Saudi Arabia,2024-03-23,Student,155824.0,782.0,High
37,C041,Ahmed,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low
39,C043,Aisha,Ansari,Male,42,Mecca,Saudi Arabia,2025-03-28,Self-Employed,80515.0,621.0,Low
42,C046,Aisha,Khan,Male,45,Dammam,Saudi Arabia,2024-05-22,Salaried,113170.0,679.0,High
44,C048,Ali,Iqbal,Female,42,Dammam,Saudi Arabia,2024-08-11,Student,174066.0,559.0,Medium
52,C056,Ali,Iqbal,Female,34,Jeddah,Saudi Arabia,2025-02-15,Student,175779.0,737.0,Low
55,C059,Aisha,Shaikh,Female,60,Jeddah,Saudi Arabia,2024-05-20,Self-Employed,60311.0,646.0,Low
58,C062,Aisha,Hussain,Female,57,Riyadh,Saudi Arabia,2025-03-14,Student,139714.0,744.0,Low
62,C066,Ahmed,Rahman,Female,31,Riyadh,Saudi Arabia,2024-05-13,Self-Employed,125813.0,608.0,Medium
65,C069,Aisha,Khan,Male,35,Jeddah,Saudi Arabia,2024-08-30,Student,69986.0,788.0,Low
69,C073,Ahmed,Malik,Male,52,Dammam,Saudi Arabia,2024-01-07,Self-Employed,168503.0,554.0,Medium
72,C076,Aisha,Farooq,Female,41,Riyadh,Saudi Arabia,2024-09-10,Self-Employed,87668.0,749.0,Low
91,C095,Ali,Iqbal,Male,56,Mecca,Saudi Arabia,2025-05-01,Salaried,110650.0,795.0,Low

In [104]:
#Which customers have missing credit scores?
df[df["credit_score"].isna()]

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, age, city, country, signup_date, employment_status, annual_income, credit_score, risk_level]
Index: []

In [ ]:
#Show the youngest five customers.
df.sort_values("age",ascending=True).head(5)

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914.0,548.0,Low
29,C030,Maryam,Farooq,Male,0,Dammam,Saudi Arabia,2024-04-21,Salaried,55979.0,660.0,Low
21,C022,Maryam,Ansari,Male,20,Riyadh,Saudi Arabia,2024-12-28,Student,55433.0,617.0,Low
43,C047,Maryam,Hussain,Female,21,Riyadh,Saudi Arabia,2025-03-25,Self-Employed,86810.0,797.0,Medium
60,C064,Noor,Hussain,Female,21,Khobar,Saudi Arabia,2024-06-21,Student,145989.0,584.0,Medium