In [ ]:
Import pandas
import pandas as pd

In [ ]:
#Load the dataset
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\pandas\customers_features.csv")

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,...,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,...,1,854,5572.333333,No,66.9,3,Adult,Medium,Excellent,High Risk
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,...,1,878,8415.833333,Yes,101.0,3,Young Adult,High,Excellent,High Risk
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,...,2,813,9410.500000,No,112.9,1,Middle Aged,High,Poor,Safe
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,...,2,435,5566.083333,No,66.8,2,Adult,Medium,Poor,Monitor
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,...,1,512,8505.541667,Yes,102.1,1,Middle Aged,High,Excellent,Safe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,...,4,626,14075.166667,No,168.9,2,Adult,High,Poor,Monitor
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,...,1,486,10538.000000,No,126.5,3,Middle Aged,High,Good,High Risk
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,...,3,693,10204.000000,No,122.4,2,Middle Aged,High,Fair,Monitor
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,...,3,714,7431.083333,No,89.2,2,Middle Aged,Medium,Excellent,Monitor
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,...,2,789,6195.333333,No,74.3,2,Young Adult,Medium,Fair,Monitor

In [30]:
#Displays the dataframe
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854,5572.333333,No,66.9,3,Adult,Medium,Excellent,High Risk
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878,8415.833333,Yes,101.0,3,Young Adult,High,Excellent,High Risk
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813,9410.500000,No,112.9,1,Middle Aged,High,Poor,Safe
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435,5566.083333,No,66.8,2,Adult,Medium,Poor,Monitor
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512,8505.541667,Yes,102.1,1,Middle Aged,High,Excellent,Safe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium,2024,October,26,Saturday,4,626,14075.166667,No,168.9,2,Adult,High,Poor,Monitor
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486,10538.000000,No,126.5,3,Middle Aged,High,Good,High Risk
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium,2024,August,20,Tuesday,3,693,10204.000000,No,122.4,2,Middle Aged,High,Fair,Monitor
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium,2024,July,30,Tuesday,3,714,7431.083333,No,89.2,2,Middle Aged,Medium,Excellent,Monitor
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium,2024,May,16,Thursday,2,789,6195.333333,No,74.3,2,Young Adult,Medium,Fair,Monitor

In [4]:
#Which city has the largest customer base?
df["city"].value_counts()

city
Riyadh    25
Khobar    21
Jeddah    18
Dammam    18
Mecca     15
Name: count, dtype: int64

In [5]:
#Which city has the highest average annual income?
df.groupby("city")["annual_income"].mean().sort_values(ascending=False)

city
Jeddah    115676.055556
Khobar    115207.952381
Dammam    109768.694444
Riyadh    100499.500000
Mecca      97622.733333
Name: annual_income, dtype: float64

In [6]:
#Which employment status has the highest average income?
df.groupby("employment_status")["annual_income"].mean().sort_values(ascending=False)

employment_status
Self-Employed    113105.941176
Salaried         107040.844828
Unknown          105091.000000
Student          102875.532258
Name: annual_income, dtype: float64

In [8]:
#Which age group has the highest average credit score?
df.groupby("age_group")["credit_score"].mean().sort_values(ascending=False)

age_group
Senior         701.750000
Middle Aged    690.777778
Adult          689.500000
Young Adult    662.125000
Name: credit_score, dtype: float64

In [9]:
#How many customers belong to each risk segment?
df["risk_segment"].value_counts()

risk_segment
Safe         38
Monitor      30
High Risk    29
Name: count, dtype: int64

In [11]:
#Which city has the most high-risk customers?
df[df["risk_segment"]=="High Risk"]["city"].value_counts()

city
Khobar    9
Jeddah    6
Riyadh    5
Dammam    5
Mecca     4
Name: count, dtype: int64

In [12]:
#How many high-value customers do we have?
df["high_value_customer"].value_counts()

high_value_customer
No     81
Yes    16
Name: count, dtype: int64

In [18]:
#Which city has the most high-value customers?
df[df["high_value_customer"]=="Yes"]["city"].value_counts()

city
Riyadh    5
Dammam    3
Jeddah    3
Mecca     3
Khobar    2
Name: count, dtype: int64

In [ ]:
#Which income band contains the most customers?
df["income_band"].value_counts()

income_band
High      51
Medium    40
Low        6
Name: count, dtype: int64

In [24]:
#What is the average annual income by age group?
df.groupby("age_group")["annual_income"].mean().sort_values(ascending=False)

age_group
Middle Aged    110906.433333
Adult          110038.987500
Senior          90185.500000
Young Adult     87638.750000
Name: annual_income, dtype: float64

In [26]:
#Which signup quarter had the most customers?
df["signup_quarter"].value_counts()

signup_quarter
1    38
2    33
4    15
3    11
Name: count, dtype: int64

In [28]:
#Which weekday had the highest number of customer signups?
df["signup_weekday"].value_counts()

signup_weekday
Tuesday      21
Friday       16
Saturday     14
Monday       14
Thursday     13
Wednesday    12
Sunday        7
Name: count, dtype: int64

In [29]:
#Display the entire dataframe
pd.set_option("display.max_columns",None)
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level,signup_year,signup_month,signup_day,signup_weekday,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,846.0,High,2024,March,12,Tuesday,1,854,5572.333333,No,66.9,3,Adult,Medium,Excellent,High Risk
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High,2024,February,17,Saturday,1,878,8415.833333,Yes,101.0,3,Young Adult,High,Excellent,High Risk
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low,2024,April,22,Monday,2,813,9410.500000,No,112.9,1,Middle Aged,High,Poor,Safe
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium,2025,May,5,Monday,2,435,5566.083333,No,66.8,2,Adult,Medium,Poor,Monitor
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,774.0,Low,2025,February,17,Monday,1,512,8505.541667,Yes,102.1,1,Middle Aged,High,Excellent,Safe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,546.0,Medium,2024,October,26,Saturday,4,626,14075.166667,No,168.9,2,Adult,High,Poor,Monitor
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,710.0,High,2025,March,15,Saturday,1,486,10538.000000,No,126.5,3,Middle Aged,High,Good,High Risk
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium,2024,August,20,Tuesday,3,693,10204.000000,No,122.4,2,Middle Aged,High,Fair,Monitor
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium,2024,July,30,Tuesday,3,714,7431.083333,No,89.2,2,Middle Aged,Medium,Excellent,Monitor
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium,2024,May,16,Thursday,2,789,6195.333333,No,74.3,2,Young Adult,Medium,Fair,Monitor