In [116]:
#Import pandas 
import pandas as pd

In [117]:
#Load the dataset 
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\customers_dirty.csv")
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,NaN,774.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
97,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448,629.0,Medium
98,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173,765.0,Medium
99,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344,647.0,Medium
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307,790.0,High
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073,779.0,Low

In [118]:
#Display the first 10 rows
df.head()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,NaN,774.0,Low

In [119]:
#Display the last 10 rows 
df.tail()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
97,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448,629.0,Medium
98,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173,765.0,Medium
99,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344,647.0,Medium
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307,790.0,High
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073,779.0,Low

In [120]:
#How many rows and columns?
df.shape

(102, 12)

In [121]:
#Display column names
df.columns

Index(['customer_id', 'first_name', 'last_name', 'gender', 'age', 'city',
       'country', 'signup_date', 'employment_status', 'annual_income',
       'credit_score', 'risk_level'],
      dtype='str')

In [122]:
#Display data types
df.dtypes

customer_id              str
first_name               str
last_name                str
gender                   str
age                    int64
city                     str
country                  str
signup_date              str
employment_status        str
annual_income            str
credit_score         float64
risk_level               str
dtype: object

In [123]:
#Display dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        102 non-null    str
 1   first_name         101 non-null    str
 2   last_name          102 non-null    str
 3   gender             102 non-null    str
 4   age                102 non-null    int64
 5   city               102 non-null    str
 6   country            102 non-null    str
 7   signup_date        102 non-null    str
 8   employment_status  101 non-null    str
 9   annual_income      101 non-null    str
 10  credit_score       101 non-null    float64
 11  risk_level         102 non-null    str
dtypes: float64(1), int64(1), str(10)
memory usage: 9.7 KB

In [ ]:
#Summary Statistics
df.describe()

              age  credit_score
count  102.000000    101.000000
mean    40.960784    691.237624
std     16.504378    115.762615
min     -5.000000    150.000000
25%     33.000000    618.000000
50%     40.000000    696.000000
75%     50.750000    782.000000
max    150.000000    950.000000

In [ ]:
#Check missing values
df.isnull().sum()

customer_id          0
first_name           1
last_name            0
gender               0
age                  0
city                 0
country              0
signup_date          0
employment_status    1
annual_income        1
credit_score         1
risk_level           0
dtype: int64

In [126]:
#Dsiplay only columns containing missing values
df.isnull().sum()[df.isnull().sum()>0]

first_name           1
employment_status    1
annual_income        1
credit_score         1
dtype: int64

In [127]:
#Count total missing values 
df.isnull().sum().sum()

np.int64(4)

In [128]:
#Count duplicate rows 
df.duplicated().sum()

np.int64(1)

In [129]:
#Are customer IDs unique 
df["customer_id"].is_unique

False

In [130]:
#Display duplicate customer IDs
df[df["customer_id"].duplicated()]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307,790.0,High
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073,779.0,Low

In [ ]:
#Checking duplicate values
df["customer_id"].duplicated().sum()

np.int64(2)

In [132]:
#Unique Gender Values 
df["gender"].unique()

<StringArray>
['Female', 'Male', ' male ', 'MALE', 'F']
Length: 5, dtype: str

In [133]:
#Count gender values
df["gender"].value_counts()

gender
Female    51
Male      48
 male      1
MALE       1
F          1
Name: count, dtype: int64

In [134]:
#Unique cities
df["city"].unique()

<StringArray>
['Jeddah', 'Riyadh', 'Khobar', 'Dammam', 'Mecca', ' riyadh ', 'RIYADH']
Length: 7, dtype: str

In [135]:
#Employment Status 
df["employment_status"].value_counts()

employment_status
Student          35
Self-Employed    34
Salaried         30
Unknown           1
-                 1
Name: count, dtype: int64

In [136]:
#Risk level counts 
df["risk_level"].value_counts()

risk_level
Low       40
High      31
Medium    31
Name: count, dtype: int64

In [137]:
#Customers younger than 18 
df[df["age"]<18]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
23,C024,Omar,Syed,Female,-5,Khobar,Saudi Arabia,2025-02-17,Self-Employed,89914,548.0,Low
29,C030,Maryam,Farooq,Male,0,Dammam,Saudi Arabia,2024-04-21,Salaried,55979,660.0,Low

In [138]:
#Customers older than 100 
df[df["age"]>100]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
24,C025,Ahmed,Malik,Female,150,Khobar,Saudi Arabia,2025-03-18,Student,54200,844.0,High

In [142]:
#Negative Income
df[df["annual_income"]<0]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
25,C026,Sara,Khan,Female,41,Riyadh,Saudi Arabia,2024-05-07,Salaried,-45000.0,774.0,Medium

In [ ]:
#Changing datatype of annual income from str to float
df["annual_income"] = pd.to_numeric(df["annual_income"],errors = "coerce")

In [ ]:
#credit scores below 300
df[df["credit_score"]<300]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
27,C028,Ali,Qureshi,Male,25,Jeddah,Saudi Arabia,2024-03-26,Self-Employed,167307.0,150.0,Low

In [ ]:
#credit score above 850 
df[df["credit_score"]>850]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
26,C027,Omar,Hussain,Male,37,Khobar,Saudi Arabia,2024-05-07,Salaried,156164.0,950.0,Low

In [ ]:
#youngest customer
df["age"].min()

np.int64(-5)

In [ ]:
#oldest customer
df["age"].max()

np.int64(150)

In [ ]:
#Display signup dates
df["signup_date"].head(10)

0    2024-03-12
1    2024-02-17
2    2024-04-22
3    2025-05-05
4    2025-02-17
5    2025-03-29
6    2024-07-13
7    2024-12-25
8    2024-07-13
9    2024-05-17
Name: signup_date, dtype: str

In [153]:
#Convert to datetime
df["signup_date"] = pd.to_datetime(df["signup_date"],format="mixed",dayfirst=True)
df["signup_date"]

0     2024-12-03
1     2024-02-17
2     2024-04-22
3     2025-05-05
4     2025-02-17
         ...
97    2024-08-20
98    2024-07-30
99    2024-05-16
100   2024-05-17
101   2025-04-28
Name: signup_date, Length: 102, dtype: datetime64[us]

In [155]:
pd.to_datetime?

Signature:
pd.to_datetime(
    arg: 'DatetimeScalarOrArrayConvertible | DictConvertible',
    errors: 'DateTimeErrorChoices' = 'raise',
    dayfirst: 'bool' = False,
    yearfirst: 'bool' = False,
    utc: 'bool' = False,
    format: 'str | None' = None,
    exact: 'bool | lib.NoDefault' = <no_default>,
    unit: 'str | None' = None,
    origin: 'str' = 'unix',
    cache: 'bool' = True,
) -> 'DatetimeIndex | Series | DatetimeScalar | NaTType'
Docstring:
Convert argument to datetime.

This function converts a scalar, array-like, :class:`Series` or
:class:`DataFrame`/dict-like to a pandas datetime object.

Parameters
----------
arg : int, float, str, datetime, list, tuple, 1-d array, Series, DataFrame/dict-like
    The object to convert to a datetime. If a :class:`DataFrame` is provided, the
    method expects minimally the following columns: :const:`"year"`,
    :const:`"month"`, :const:`"day"`. The column "year"
    must be specified in 4-digit format.
errors : {'raise', 'coerce'}, default 'raise'
    - If :const:`'raise'`, then invalid parsing will raise an exception.
    - If :const:`'coerce'`, then invalid parsing will be set as :const:`NaT`.
dayfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.
    If :const:`True`, parses dates with the day first, e.g. :const:`"10/11/12"`
    is parsed as :const:`2012-11-10`.

    .. warning::

        ``dayfirst=True`` is not strict, but will prefer to parse
        with day first.

yearfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.

    - If :const:`True` parses dates with the year first, e.g.
      :const:`"10/11/12"` is parsed as :const:`2010-11-12`.
    - If both `dayfirst` and `yearfirst` are :const:`True`, `yearfirst` is
      preceded (same as :mod:`dateutil`).

    .. warning::

        ``yearfirst=True`` is not strict, but will prefer to parse
        with year first.

utc : bool, default False
    Control timezone-related parsing, localization and conversion.

    - If :const:`True`, the function *always* returns a timezone-aware
      UTC-localized :class:`Timestamp`, :class:`Series` or
      :class:`DatetimeIndex`. To do this, timezone-naive inputs are
      *localized* as UTC, while timezone-aware inputs are *converted* to UTC.

    - If :const:`False` (default), inputs will not be coerced to UTC.
      Timezone-naive inputs will remain naive, while timezone-aware ones
      will keep their time offsets. Limitations exist for mixed
      offsets (typically, daylight savings), see :ref:`Examples
      <to_datetime_tz_examples>` section for details.

    See also: pandas general documentation about `timezone conversion and
    localization
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
    #time-zone-handling>`_.

format : str, default None
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.

    .. note::

        If a :class:`DataFrame` is passed, then `format` has no effect.

exact : bool, default True
    Control how `format` is used:

    - If :const:`True`, require an exact `format` match.
    - If :const:`False`, allow the `format` to match anywhere in the target
      string.

    Cannot be used alongside ``format='ISO8601'`` or ``format='mixed'``.
unit : str, default 'ns'
    The unit of the arg (D,s,ms,us,ns) denote the unit, which is an
    integer or float number. This will be based off the origin.
    Example, with ``unit='ms'`` and ``origin='unix'``, this would calculate
    the number of milliseconds to the unix epoch start.
origin : scalar, default 'unix'
    Define the reference date. The numeric values would be parsed as number
    of units (defined by `unit`) since this reference date.

    - If :const:`'unix'` (or POSIX) time; origin is set to 1970-01-01.
    - If :const:`'julian'`, unit must be :const:`'D'`, and origin is set to
      beginning of Julian Calendar. Julian day number :const:`0` is assigned
      to the day starting at noon on January 1, 4713 BC.
    - If Timestamp convertible (Timestamp, dt.datetime, np.datetimt64 or date
      string), origin is set to Timestamp identified by origin.
    - If a float or integer, origin is the difference
      (in units determined by the ``unit`` argument) relative to 1970-01-01.
cache : bool, default True
    If :const:`True`, use a cache of unique, converted dates to apply the
    datetime conversion. May produce significant speed-up when parsing
    duplicate date strings, especially ones with timezone offsets. The cache
    is only used when there are at least 50 values. The presence of
    out-of-bounds values will render the cache unusable and may slow down
    parsing.

Returns
-------
datetime
    If parsing succeeded.
    Return type depends on input (types in parenthesis correspond to
    fallback in case of unsuccessful timezone or out-of-range timestamp
    parsing):

    - scalar: :class:`Timestamp` (or :class:`datetime.datetime`)
    - array-like: :class:`DatetimeIndex` (or :class:`Series` with
      :class:`object` dtype containing :class:`datetime.datetime`)
    - Series: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)
    - DataFrame: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)

Raises
------
ParserError
    When parsing a date from string fails.
ValueError
    When another datetime conversion error happens. For example when one
    of 'year', 'month', day' columns is missing in a :class:`DataFrame`, or
    when a Timezone-aware :class:`datetime.datetime` is found in an array-like
    of mixed time offsets, and ``utc=False``, or when parsing datetimes
    with mixed time zones unless ``utc=True``. If parsing datetimes with mixed
    time zones, please specify ``utc=True``.

See Also
--------
DataFrame.astype : Cast argument to a specified dtype.
to_timedelta : Convert argument to timedelta.
convert_dtypes : Convert dtypes.

Notes
-----

Many input types are supported, and lead to different output types:

- **scalars** can be int, float, str, datetime object (from stdlib :mod:`datetime`
  module or :mod:`numpy`). They are converted to :class:`Timestamp` when
  possible, otherwise they are converted to :class:`datetime.datetime`.
  None/NaN/null scalars are converted to :const:`NaT`.

- **array-like** can contain int, float, str, datetime objects. They are
  converted to :class:`DatetimeIndex` when possible, otherwise they are
  converted to :class:`Index` with :class:`object` dtype, containing
  :class:`datetime.datetime`. None/NaN/null entries are converted to
  :const:`NaT` in both cases.

- **Series** are converted to :class:`Series` with :class:`datetime64`
  dtype when possible, otherwise they are converted to :class:`Series` with
  :class:`object` dtype, containing :class:`datetime.datetime`. None/NaN/null
  entries are converted to :const:`NaT` in both cases.

- **DataFrame/dict-like** are converted to :class:`Series` with
  :class:`datetime64` dtype. For each row a datetime is created from assembling
  the various dataframe columns. Column keys can be common abbreviations
  like ['year', 'month', 'day', 'minute', 'second', 'ms', 'us', 'ns']) or
  plurals of the same.

The following causes are responsible for :class:`datetime.datetime` objects
being returned (possibly inside an :class:`Index` or a :class:`Series` with
:class:`object` dtype) instead of a proper pandas designated type
(:class:`Timestamp`, :class:`DatetimeIndex` or :class:`Series`
with :class:`datetime64` dtype):

- when any input element is before :const:`Timestamp.min` or after
  :const:`Timestamp.max`, see `timestamp limitations
  <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
  #timeseries-timestamp-limits>`_.

- when ``utc=False`` (default) and the input is an array-like or
  :class:`Series` containing mixed naive/aware datetime, or aware with mixed
  time offsets. Note that this happens in the (quite frequent) situation when
  the timezone has a daylight savings policy. In that case you may wish to
  use ``utc=True``.

Examples
--------

**Handling various input formats**

Assembling a datetime from multiple columns of a :class:`DataFrame`. The keys
can be common abbreviations like ['year', 'month', 'day', 'minute', 'second',
'ms', 'us', 'ns']) or plurals of the same

>>> df = pd.DataFrame({"year": [2015, 2016], "month": [2, 3], "day": [4, 5]})
>>> pd.to_datetime(df)
0   2015-02-04
1   2016-03-05
dtype: datetime64[us]

Using a unix epoch time

>>> pd.to_datetime(1490195805, unit="s")
Timestamp('2017-03-22 15:16:45')
>>> pd.to_datetime(1490195805433502912, unit="ns")
Timestamp('2017-03-22 15:16:45.433502912')

.. warning:: For float arg, precision rounding might happen. To prevent
    unexpected behavior use a fixed-width exact type.

Using a non-unix epoch origin

>>> pd.to_datetime([1, 2, 3], unit="D", origin=pd.Timestamp("1960-01-01"))
DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'],
              dtype='datetime64[s]', freq=None)

**Differences with strptime behavior**

:const:`"%f"` will parse all the way up to nanoseconds.

>>> pd.to_datetime("2018-10-26 12:00:00.0000000011", format="%Y-%m-%d %H:%M:%S.%f")
Timestamp('2018-10-26 12:00:00.000000001')

**Non-convertible date/times**

Passing ``errors='coerce'`` will force an out-of-bounds date to :const:`NaT`,
in addition to forcing non-dates (or non-parseable dates) to :const:`NaT`.

>>> pd.to_datetime("invalid for Ymd", format="%Y%m%d", errors="coerce")
NaT

.. _to_datetime_tz_examples:

**Timezones and time offsets**

The default behaviour (``utc=False``) is as follows:

- Timezone-naive inputs are converted to timezone-naive :class:`DatetimeIndex`:

>>> pd.to_datetime(["2018-10-26 12:00:00", "2018-10-26 13:00:15"])
DatetimeIndex(['2018-10-26 12:00:00', '2018-10-26 13:00:15'],
              dtype='datetime64[us]', freq=None)

- Timezone-aware inputs *with constant time offset* are converted to
  timezone-aware :class:`DatetimeIndex`:

>>> pd.to_datetime(["2018-10-26 12:00 -0500", "2018-10-26 13:00 -0500"])
DatetimeIndex(['2018-10-26 12:00:00-05:00', '2018-10-26 13:00:00-05:00'],
              dtype='datetime64[us, UTC-05:00]', freq=None)

- However, timezone-aware inputs *with mixed time offsets* (for example
  issued from a timezone with daylight savings, such as Europe/Paris)
  are **not successfully converted** to a :class:`DatetimeIndex`.
  Parsing datetimes with mixed time zones will raise a ValueError unless
  ``utc=True``:

>>> pd.to_datetime(
...     ["2020-10-25 02:00 +0200", "2020-10-25 04:00 +0100"]
... )  # doctest: +SKIP
ValueError: Mixed timezones detected. Pass utc=True in to_datetime
or tz='UTC' in DatetimeIndex to convert to a common timezone.

- To create a :class:`Series` with mixed offsets and ``object`` dtype, please use
  :meth:`Series.apply` and :func:`datetime.datetime.strptime`:

>>> import datetime as dt
>>> ser = pd.Series(["2020-10-25 02:00 +0200", "2020-10-25 04:00 +0100"])
>>> ser.apply(lambda x: dt.datetime.strptime(x, "%Y-%m-%d %H:%M %z"))
0    2020-10-25 02:00:00+02:00
1    2020-10-25 04:00:00+01:00
dtype: object

- A mix of timezone-aware and timezone-naive inputs will also raise a ValueError
  unless ``utc=True``:

>>> from datetime import datetime
>>> pd.to_datetime(
...     ["2020-01-01 01:00:00-01:00", datetime(2020, 1, 1, 3, 0)]
... )  # doctest: +SKIP
ValueError: Mixed timezones detected. Pass utc=True in to_datetime
or tz='UTC' in DatetimeIndex to convert to a common timezone.

|

Setting ``utc=True`` solves most of the above issues:

- Timezone-naive inputs are *localized* as UTC

>>> pd.to_datetime(["2018-10-26 12:00", "2018-10-26 13:00"], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2018-10-26 13:00:00+00:00'],
              dtype='datetime64[us, UTC]', freq=None)

- Timezone-aware inputs are *converted* to UTC (the output represents the
  exact same datetime, but viewed from the UTC time offset `+00:00`).

>>> pd.to_datetime(["2018-10-26 12:00 -0530", "2018-10-26 12:00 -0500"], utc=True)
DatetimeIndex(['2018-10-26 17:30:00+00:00', '2018-10-26 17:00:00+00:00'],
              dtype='datetime64[us, UTC]', freq=None)

- Inputs can contain both string or datetime, the above
  rules still apply

>>> pd.to_datetime(["2018-10-26 12:00", datetime(2020, 1, 1, 18)], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2020-01-01 18:00:00+00:00'],
              dtype='datetime64[us, UTC]', freq=None)
File:      c:\users\marya\appdata\local\programs\python\python314\lib\site-packages\pandas\core\tools\datetimes.py
Type:      function

In [156]:
df.head()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-12-03,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,NaN,774.0,Low

In [160]:
df[df["customer_id"].duplicated()]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307.0,790.0,High
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low

In [164]:
#Check for leading and trailing spaces in string columns
df["city"] = df["city"].str.strip()

In [166]:
df[df["customer_id"].str.startswith("C")]

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-12-03,Student,66868.0,846.0,High
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,758.0,High
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,503.0,Low
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,547.0,Medium
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,NaN,774.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
97,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,629.0,Medium
98,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,765.0,Medium
99,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,647.0,Medium
100,C010,Ali,Ansari,Male,40,Khobar,Saudi Arabia,2024-05-17,Salaried,95307.0,790.0,High
101,C041,Different,Qureshi,Male,27,Riyadh,Saudi Arabia,2025-04-28,Student,79073.0,779.0,Low

In [171]:
df["city"].nunique()

7

In [172]:
df["employment_status"].nunique()

5

In [173]:
df["country"].nunique()

2

In [174]:
df["city"].value_counts()

city
Riyadh    24
Khobar    23
Jeddah    19
Dammam    18
Mecca     16
riyadh     1
RIYADH     1
Name: count, dtype: int64

In [175]:
df["employment_status"].value_counts()

employment_status
Student          35
Self-Employed    34
Salaried         30
Unknown           1
-                 1
Name: count, dtype: int64

In [176]:
df["risk_level"].value_counts()

risk_level
Low       40
High      31
Medium    31
Name: count, dtype: int64