In [ ]:
#Import pandas library
import pandas as pd 

#Read the CSV File
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\customers.csv")

In [ ]:
#Display the dataset
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,1,First1,Last1,Male,35,Riyadh,Saudi Arabia,2023-09-08,Employed,48289,552,High
1,2,First2,Last2,Male,55,Doha,Qatar,2024-03-08,Employed,33905,547,Low
2,3,First3,Last3,Male,53,Jeddah,Saudi Arabia,2023-07-23,Self-employed,115181,779,Medium
3,4,First4,Last4,Female,55,Jeddah,Saudi Arabia,2023-10-12,Employed,129458,581,High
4,5,First5,Last5,Female,35,Abu Dhabi,UAE,2023-06-09,Employed,130072,672,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,First96,Last96,Female,56,Riyadh,Saudi Arabia,2025-04-04,Employed,134363,789,Low
96,97,First97,Last97,Female,60,Dubai,UAE,2024-01-15,Employed,96317,831,Medium
97,98,First98,Last98,Female,49,Riyadh,Saudi Arabia,2023-04-19,Student,77472,825,Medium
98,99,First99,Last99,Female,29,Jeddah,Saudi Arabia,2025-01-21,Self-employed,115256,638,High
99,100,First100,Last100,Female,47,Doha,Qatar,2024-03-22,Self-employed,107656,637,Medium

In [ ]:
#Display the first five rows
df.head()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
0,1,First1,Last1,Male,35,Riyadh,Saudi Arabia,2023-09-08,Employed,48289,552,High
1,2,First2,Last2,Male,55,Doha,Qatar,2024-03-08,Employed,33905,547,Low
2,3,First3,Last3,Male,53,Jeddah,Saudi Arabia,2023-07-23,Self-employed,115181,779,Medium
3,4,First4,Last4,Female,55,Jeddah,Saudi Arabia,2023-10-12,Employed,129458,581,High
4,5,First5,Last5,Female,35,Abu Dhabi,UAE,2023-06-09,Employed,130072,672,Low

In [ ]:
#Display the last five rows
df.tail()

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,credit_score,risk_level
95,96,First96,Last96,Female,56,Riyadh,Saudi Arabia,2025-04-04,Employed,134363,789,Low
96,97,First97,Last97,Female,60,Dubai,UAE,2024-01-15,Employed,96317,831,Medium
97,98,First98,Last98,Female,49,Riyadh,Saudi Arabia,2023-04-19,Student,77472,825,Medium
98,99,First99,Last99,Female,29,Jeddah,Saudi Arabia,2025-01-21,Self-employed,115256,638,High
99,100,First100,Last100,Female,47,Doha,Qatar,2024-03-22,Self-employed,107656,637,Medium

In [ ]:
#Display dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        100 non-null    int64
 1   first_name         100 non-null    str
 2   last_name          100 non-null    str
 3   gender             100 non-null    str
 4   age                100 non-null    int64
 5   city               100 non-null    str
 6   country            100 non-null    str
 7   signup_date        100 non-null    str
 8   employment_status  100 non-null    str
 9   annual_income      100 non-null    int64
 10  credit_score       100 non-null    int64
 11  risk_level         100 non-null    str
dtypes: int64(4), str(8)
memory usage: 9.5 KB

In [10]:
#Display descriptive statistics
df.describe()

       customer_id         age  annual_income  credit_score
count   100.000000  100.000000     100.000000    100.000000
mean     50.500000   40.070000   95474.730000    673.220000
std      29.011492   13.337314   32456.571815    101.580399
min       1.000000   18.000000   30726.000000    501.000000
25%      25.750000   26.750000   69047.250000    580.500000
50%      50.500000   41.500000  101592.000000    660.500000
75%      75.250000   53.000000  120607.250000    765.750000
max     100.000000   60.000000  148479.000000    849.000000

In [ ]:
#Count missing values in each column
df.isnull().sum()

customer_id          0
first_name           0
last_name            0
gender               0
age                  0
city                 0
country              0
signup_date          0
employment_status    0
annual_income        0
credit_score         0
risk_level           0
dtype: int64

In [14]:
#Count duplicate rows 
df.duplicated().sum()

np.int64(0)

In [ ]:
#Returns the number of rows and columns
df.shape

(100, 12)

Key observations:

- The dataset contains 100 customer records 
- No duplicate customer IDs were found 
- No missing values were found in the dataset