In [329]:
#Import pandas and numpy
import pandas as pd 
import numpy as np

In [402]:
#Load the customers dataset
df = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\pandas\customers_features.csv")
df

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,...,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,...,1,854,5572.333333,No,66.9,3,Adult,Medium,Excellent,High Risk
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,...,1,878,8415.833333,Yes,101.0,3,Young Adult,High,Excellent,High Risk
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,...,2,813,9410.500000,No,112.9,1,Middle Aged,High,Poor,Safe
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,...,2,435,5566.083333,No,66.8,2,Adult,Medium,Poor,Monitor
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,...,1,512,8505.541667,Yes,102.1,1,Middle Aged,High,Excellent,Safe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,...,4,626,14075.166667,No,168.9,2,Adult,High,Poor,Monitor
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,...,1,486,10538.000000,No,126.5,3,Middle Aged,High,Good,High Risk
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,...,3,693,10204.000000,No,122.4,2,Middle Aged,High,Fair,Monitor
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,...,3,714,7431.083333,No,89.2,2,Middle Aged,Medium,Excellent,Monitor
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,...,2,789,6195.333333,No,74.3,2,Young Adult,Medium,Fair,Monitor

In [ ]:
#Load the transactions dataset
df2 = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\transactions.csv")
df2

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True
...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False

In [ ]:
#Load the merchant dataset 
df3 = pd.read_csv(r"C:\Users\marya\OneDrive\Desktop\fintech\finpay-data-analytics-roadmap\datasets\merchants.csv")
df3

,merchant_id,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
0,1,Merchant1,Electronics,Jeddah,Saudi Arabia,2023-10-13,4.53,3.5,True
1,2,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
2,3,Merchant3,Restaurant,Jeddah,Saudi Arabia,2023-08-06,2.42,3.5,True
3,4,Merchant4,Grocery,Doha,Qatar,2024-07-23,1.04,4.9,True
4,5,Merchant5,Restaurant,Jeddah,Saudi Arabia,2024-05-15,3.22,3.5,True
5,6,Merchant6,Restaurant,Abu Dhabi,UAE,2025-03-22,1.07,3.6,True
6,7,Merchant7,Grocery,Jeddah,Saudi Arabia,2024-11-10,3.33,3.9,False
7,8,Merchant8,Restaurant,Dubai,UAE,2025-02-02,3.20,3.7,True
8,9,Merchant9,Grocery,Dubai,UAE,2023-09-15,1.92,4.4,True
9,10,Merchant10,Travel,Riyadh,Saudi Arabia,2025-02-19,3.76,3.4,False
10,11,Merchant11,Grocery,Abu Dhabi,UAE,2025-01-11,3.36,4.5,False
11,12,Merchant12,Electronics,Dubai,UAE,2025-05-02,1.78,3.5,True
12,13,Merchant13,Electronics,Dubai,UAE,2024-12-26,3.14,3.5,True
13,14,Merchant14,Grocery,Doha,Qatar,2024-12-15,4.78,4.3,True
14,15,Merchant15,Electronics,Riyadh,Saudi Arabia,2024-08-10,2.14,4.0,True
15,16,Merchant16,Electronics,Jeddah,Saudi Arabia,2023-09-16,4.76,4.0,True
16,17,Merchant17,Restaurant,Abu Dhabi,UAE,2023-03-17,3.31,4.4,True
17,18,Merchant18,Travel,Jeddah,Saudi Arabia,2023-11-08,1.34,3.5,False
18,19,Merchant19,Travel,Abu Dhabi,UAE,2024-09-02,4.16,3.5,False
19,20,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True

In [ ]:
#Display the first 5 rows of customer dataset
df.head(5)

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,...,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
0,C001,Sara,Khan,Female,35,Jeddah,Saudi Arabia,2024-03-12,Student,66868.0,...,1,854,5572.333333,No,66.9,3,Adult,Medium,Excellent,High Risk
1,C002,Maryam,Iqbal,Female,22,Riyadh,Saudi Arabia,2024-02-17,Salaried,100990.0,...,1,878,8415.833333,Yes,101.0,3,Young Adult,High,Excellent,High Risk
2,C003,Ali,Qureshi,Male,54,Khobar,Saudi Arabia,2024-04-22,Self-Employed,112926.0,...,2,813,9410.500000,No,112.9,1,Middle Aged,High,Poor,Safe
3,C004,Ahmed,Malik,Female,29,Jeddah,Saudi Arabia,2025-05-05,Self-Employed,66793.0,...,2,435,5566.083333,No,66.8,2,Adult,Medium,Poor,Monitor
4,C005,Sara,Malik,Female,58,Dammam,Saudi Arabia,2025-02-17,Salaried,102066.5,...,1,512,8505.541667,Yes,102.1,1,Middle Aged,High,Excellent,Safe

In [ ]:
#Display the first 5 rows of the transactions dataset 
df2.head(5)

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True

In [ ]:
#Display the first 5 rows of the merchant dataset
df3.head(5)

,merchant_id,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
0,1,Merchant1,Electronics,Jeddah,Saudi Arabia,2023-10-13,4.53,3.5,True
1,2,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
2,3,Merchant3,Restaurant,Jeddah,Saudi Arabia,2023-08-06,2.42,3.5,True
3,4,Merchant4,Grocery,Doha,Qatar,2024-07-23,1.04,4.9,True
4,5,Merchant5,Restaurant,Jeddah,Saudi Arabia,2024-05-15,3.22,3.5,True

In [ ]:
#Display the last 5 rows of the customers dataset
df.tail(5)

,customer_id,first_name,last_name,gender,age,city,country,signup_date,employment_status,annual_income,...,signup_quarter,customer_tenure_days,monthly_income,high_value_customer,annual_income_k,risk_score,age_group,income_band,credit_score_category,risk_segment
92,C096,Omar,Farooq,Female,37,Jeddah,Saudi Arabia,2024-10-26,Self-Employed,168902.0,...,4,626,14075.166667,No,168.9,2,Adult,High,Poor,Monitor
93,C097,Fatima,Hussain,Female,40,Riyadh,Saudi Arabia,2025-03-15,Salaried,126456.0,...,1,486,10538.000000,No,126.5,3,Middle Aged,High,Good,High Risk
94,C098,Lina,Shaikh,Female,55,Riyadh,Saudi Arabia,2024-08-20,Salaried,122448.0,...,3,693,10204.000000,No,122.4,2,Middle Aged,High,Fair,Monitor
95,C099,Sara,Hussain,Male,54,Khobar,Saudi Arabia,2024-07-30,Salaried,89173.0,...,3,714,7431.083333,No,89.2,2,Middle Aged,Medium,Excellent,Monitor
96,C100,Zaid,Farooq,Female,23,Jeddah,Saudi Arabia,2024-05-16,Student,74344.0,...,2,789,6195.333333,No,74.3,2,Young Adult,Medium,Fair,Monitor

In [ ]:
#Display the last 5 transactions dataset
df2.tail(5)

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False

In [ ]:
#Display the last 5 merchant dataset
df3.tail(5)

,merchant_id,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
15,16,Merchant16,Electronics,Jeddah,Saudi Arabia,2023-09-16,4.76,4.0,True
16,17,Merchant17,Restaurant,Abu Dhabi,UAE,2023-03-17,3.31,4.4,True
17,18,Merchant18,Travel,Jeddah,Saudi Arabia,2023-11-08,1.34,3.5,False
18,19,Merchant19,Travel,Abu Dhabi,UAE,2024-09-02,4.16,3.5,False
19,20,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True

In [ ]:
#Show the rows and columns of the customer dataset
df.shape

(97, 26)

In [ ]:
#Show the rows and columns of the transactions dataset
df2.shape

(500, 10)

In [403]:
#Shows the rows and columns of the merchants dataset
df3.shape

(20, 9)

In [404]:
#Show the customer datatypes
df.dtypes

customer_id                  str
first_name                   str
last_name                    str
gender                       str
age                        int64
city                         str
country                      str
signup_date                  str
employment_status            str
annual_income            float64
credit_score             float64
risk_level                   str
signup_year                int64
signup_month                 str
signup_day                 int64
signup_weekday               str
signup_quarter             int64
customer_tenure_days       int64
monthly_income           float64
high_value_customer          str
annual_income_k          float64
risk_score                 int64
age_group                    str
income_band                  str
credit_score_category        str
risk_segment                 str
dtype: object

In [ ]:
#Showw the transactions datatypes
df2.dtypes

transaction_id          int64
customer_id             int64
merchant_id             int64
transaction_date          str
amount                float64
payment_method            str
transaction_status        str
installment_months      int64
cashback              float64
wallet_used              bool
dtype: object

In [405]:
#Show the merchant datatypes
df3.dtypes

merchant_id          int64
merchant_name          str
category               str
city                   str
country                str
onboarding_date        str
commission_rate    float64
rating             float64
active_status         bool
dtype: object

Identify the primary key of each table

customers -> customer_id

transactions -> transaction_id

merchants -> merchant_id

In [ ]:
#Check missing values in customer tables
customers.isnull().sum()

customer_id              0
first_name               0
last_name                0
gender                   0
age                      0
city                     0
country                  0
signup_date              0
employment_status        0
annual_income            0
credit_score             0
risk_level               0
signup_year              0
signup_month             0
signup_day               0
signup_weekday           0
signup_quarter           0
customer_tenure_days     0
monthly_income           0
high_value_customer      0
annual_income_k          0
risk_score               0
age_group                0
income_band              0
credit_score_category    0
risk_segment             0
dtype: int64

In [ ]:
#Check missing values in transactions
transactions.isnull().sum()

transaction_id        0
customer_id           0
merchant_id           0
transaction_date      0
amount                0
payment_method        0
transaction_status    0
installment_months    0
cashback              0
wallet_used           0
dtype: int64

In [ ]:
#Check mmissing values in merchants
merchants.isnull().sum()

merchant_id        0
merchant_name      0
category           0
city               0
country            0
onboarding_date    0
commission_rate    0
rating             0
active_status      0
dtype: int64

In [348]:
#Check duplicate customer IDs
df["customer_id"].duplicated().sum()

np.int64(0)

In [349]:
#Check duplicate merchant IDs 
df3["merchant_id"].duplicated().sum()

np.int64(0)

In [350]:
#Check duplicate transaction IDs
df2["transaction_id"].duplicated().sum()

np.int64(0)

In [355]:
#isin() checks whether each customer ID in the customers df exists transactions df
#the .sum() adds up the True and False
#if there are 3 customer IDs from the customer table also exist in the transactions table
#What if the result is 0? None of the customer IDs in customer exist in transactions
#If you have 100 customers, every customer has atleast one matching transaction 
#Verify matching customer IDs
df["customer_id"].isin(df2["customer_id"]).value_counts()

customer_id
False    97
Name: count, dtype: int64

In [356]:
#Verify matching merchant IDs
df2["merchant_id"].isin(df3["merchant_id"]).value_counts()

merchant_id
True    500
Name: count, dtype: int64

In [ ]:
#Convert the customer_id data type from customer table from str to object
df["customer_id"] = df["customer_id"].astype(object)

In [ ]:
#Convert the customer_id data type from transactions tables from str to object
df2["customer_id"] = df2["customer_id"].astype(object)

In [409]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            97 non-null     str
 1   first_name             97 non-null     str
 2   last_name              97 non-null     str
 3   gender                 97 non-null     str
 4   age                    97 non-null     int64
 5   city                   97 non-null     str
 6   country                97 non-null     str
 7   signup_date            97 non-null     str
 8   employment_status      97 non-null     str
 9   annual_income          97 non-null     float64
 10  credit_score           97 non-null     float64
 11  risk_level             97 non-null     str
 12  signup_year            97 non-null     int64
 13  signup_month           97 non-null     str
 14  signup_day             97 non-null     int64
 15  signup_weekday         97 non-null     str
 16  signup_quarter         97 non-null     int64
 17  customer_tenure_days   97 non-null     int64
 18  monthly_income         97 non-null     float64
 19  high_value_customer    97 non-null     str
 20  annual_income_k        97 non-null     float64
 21  risk_score             97 non-null     int64
 22  age_group              97 non-null     str
 23  income_band            97 non-null     str
 24  credit_score_category  97 non-null     str
 25  risk_segment           97 non-null     str
dtypes: float64(4), int64(6), str(16)
memory usage: 19.8 KB

In [ ]:
#Merge transaction and merchant tables together on merchant_id as merged files
transactions_merchants = pd.merge(df2,df3,on="merchant_id",how="inner")
transactions_merchants.columns

Index(['transaction_id', 'customer_id', 'merchant_id', 'transaction_date',
       'amount', 'payment_method', 'transaction_status', 'installment_months',
       'cashback', 'wallet_used', 'merchant_name', 'category', 'city',
       'country', 'onboarding_date', 'commission_rate', 'rating',
       'active_status'],
      dtype='str')

In [ ]:
#Check the merged files rows and columns
ransactions_merchants.shape

(500, 18)

In [364]:
transactions_merchants

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True,Merchant6,Restaurant,Abu Dhabi,UAE,2025-03-22,1.07,3.6,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True,Merchant15,Electronics,Riyadh,Saudi Arabia,2024-08-10,2.14,4.0,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True,Merchant8,Restaurant,Dubai,UAE,2025-02-02,3.20,3.7,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True,Merchant17,Restaurant,Abu Dhabi,UAE,2023-03-17,3.31,4.4,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True,Merchant13,Electronics,Dubai,UAE,2024-12-26,3.14,3.5,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False,Merchant3,Restaurant,Jeddah,Saudi Arabia,2023-08-06,2.42,3.5,True

In [410]:
transactions_merchants.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      500 non-null    object
 1   customer_id         500 non-null    object
 2   merchant_id         500 non-null    object
 3   transaction_date    500 non-null    datetime64[us]
 4   amount              500 non-null    float64
 5   payment_method      500 non-null    str
 6   transaction_status  500 non-null    str
 7   installment_months  500 non-null    int64
 8   cashback            500 non-null    float64
 9   wallet_used         500 non-null    bool
 10  merchant_name       500 non-null    str
 11  category            500 non-null    str
 12  city                500 non-null    str
 13  country             500 non-null    str
 14  onboarding_date     500 non-null    str
 15  commission_rate     500 non-null    float64
 16  rating              500 non-null    float64
 17  active_status       500 non-null    bool
dtypes: bool(2), datetime64[us](1), float64(4), int64(1), object(3), str(7)
memory usage: 63.6+ KB

In [ ]:
#Convert the transaction_id from str to object
transactions_merchants["transaction_id"] = transactions_merchants["transaction_id"].astype(object)

In [ ]:
#Convert the merchant_id from str to object
transactions_merchants["merchant_id"] = transactions_merchants["merchant_id"].astype(object)

In [ ]:
#Convert the transaction_date from str to datetime
transactions_merchants["transaction_date"] = pd.to_datetime(transactions_merchants["transaction_date"])

In [ ]:
transactions_merchants.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      500 non-null    object
 1   customer_id         500 non-null    object
 2   merchant_id         500 non-null    object
 3   transaction_date    500 non-null    datetime64[us]
 4   amount              500 non-null    float64
 5   payment_method      500 non-null    str
 6   transaction_status  500 non-null    str
 7   installment_months  500 non-null    int64
 8   cashback            500 non-null    float64
 9   wallet_used         500 non-null    bool
 10  merchant_name       500 non-null    str
 11  category            500 non-null    str
 12  city                500 non-null    str
 13  country             500 non-null    str
 14  onboarding_date     500 non-null    str
 15  commission_rate     500 non-null    float64
 16  rating              500 non-null    float64
 17  active_status       500 non-null    bool
dtypes: bool(2), datetime64[us](1), float64(4), int64(1), object(3), str(7)
memory usage: 63.6+ KB

In [369]:
#What is the total transaction value processed? 
transactions_merchants["amount"].sum().round(2)

np.float64(746598.64)

In [370]:
transactions_merchants

,transaction_id,customer_id,merchant_id,transaction_date,amount,payment_method,transaction_status,installment_months,cashback,wallet_used,merchant_name,category,city,country,onboarding_date,commission_rate,rating,active_status
0,1,80,2,2024-06-05,923.09,Card,Success,12,18.46,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
1,2,11,6,2024-03-02,801.29,Apple Pay,Success,3,16.03,True,Merchant6,Restaurant,Abu Dhabi,UAE,2025-03-22,1.07,3.6,True
2,3,89,20,2024-04-30,1231.47,Google Pay,Success,3,24.63,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
3,4,90,15,2024-01-19,2123.80,Apple Pay,Failed,12,42.48,True,Merchant15,Electronics,Riyadh,Saudi Arabia,2024-08-10,2.14,4.0,True
4,5,70,8,2024-06-14,1281.17,Apple Pay,Failed,3,25.62,True,Merchant8,Restaurant,Dubai,UAE,2025-02-02,3.20,3.7,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,52,20,2024-06-16,2792.75,Google Pay,Success,3,55.86,False,Merchant20,Restaurant,Abu Dhabi,UAE,2024-03-29,2.19,4.2,True
496,497,26,17,2024-03-14,1322.53,Apple Pay,Success,12,26.45,True,Merchant17,Restaurant,Abu Dhabi,UAE,2023-03-17,3.31,4.4,True
497,498,87,2,2024-04-02,1849.42,Apple Pay,Success,3,36.99,True,Merchant2,Travel,Doha,Qatar,2024-11-15,2.52,3.1,True
498,499,100,13,2024-03-31,2990.48,Wallet,Failed,12,59.81,True,Merchant13,Electronics,Dubai,UAE,2024-12-26,3.14,3.5,True
499,500,95,3,2024-01-24,1558.05,Google Pay,Failed,6,31.16,False,Merchant3,Restaurant,Jeddah,Saudi Arabia,2023-08-06,2.42,3.5,True

Finance Analytics

In [371]:
#What is the average transaction amount?
transactions_merchants["amount"].mean().round(2)

np.float64(1493.2)

In [372]:
#What is the largest transaction?
transactions_merchants["amount"].max()

np.float64(2999.93)

In [373]:
#What is the smallest transaction?
transactions_merchants["amount"].min()

np.float64(18.19)

Marketing Analytics

In [374]:
#Which merchant generated the highest revenue?
transactions_merchants.groupby("merchant_name")["amount"].sum().sort_values(ascending=False)

merchant_name
Merchant2     50432.04
Merchant16    49256.89
Merchant18    45140.36
Merchant20    45043.19
Merchant15    43959.26
Merchant3     42115.41
Merchant10    42069.30
Merchant5     40467.96
Merchant19    40281.21
Merchant17    36696.60
Merchant13    36384.63
Merchant4     35496.33
Merchant6     35287.18
Merchant11    34549.59
Merchant14    32441.27
Merchant12    32188.56
Merchant9     29462.93
Merchant7     29072.50
Merchant1     25004.47
Merchant8     21248.96
Name: amount, dtype: float64

In [375]:
#Which merchant category generated the highest revenue?
transactions_merchants.groupby("category")["amount"].sum().sort_values(ascending=False)

category
Restaurant     220859.30
Electronics    186793.81
Travel         177922.91
Grocery        161022.62
Name: amount, dtype: float64

In [377]:
#Which merchant processed the most transaction?
transactions_merchants.groupby("merchant_name")["transaction_id"].count().sort_values(ascending=False)

merchant_name
Merchant20    34
Merchant10    32
Merchant2     32
Merchant19    31
Merchant3     30
Merchant18    28
Merchant16    28
Merchant15    28
Merchant5     25
Merchant4     25
Merchant11    24
Merchant6     23
Merchant13    23
Merchant8     23
Merchant17    22
Merchant14    19
Merchant9     19
Merchant1     18
Merchant12    18
Merchant7     18
Name: transaction_id, dtype: int64

In [378]:
#Which merchant category has the highest average transaction amount?
transactions_merchants.groupby("category")["amount"].mean().sort_values(ascending=False)

category
Electronics    1624.294000
Grocery        1533.548762
Travel         1446.527724
Restaurant     1406.747134
Name: amount, dtype: float64

Payment Analytics

In [379]:
#Which payment method is most popular?
transactions_merchants["payment_method"].value_counts()

payment_method
Google Pay    152
Wallet        119
Apple Pay     117
Card          112
Name: count, dtype: int64

In [380]:
#Which payment method generated the highest revenue?
transactions_merchants.groupby("payment_method")["amount"].sum().sort_values(ascending=False)

payment_method
Google Pay    229172.58
Wallet        179740.00
Apple Pay     176250.72
Card          161435.34
Name: amount, dtype: float64

In [381]:
#Which payment method has the highest average transaction value?
transactions_merchants.groupby("payment_method")["amount"].mean().sort_values(ascending=False)

payment_method
Wallet        1510.420168
Google Pay    1507.714342
Apple Pay     1506.416410
Card          1441.386964
Name: amount, dtype: float64

Cashback Analytics

In [382]:
#How much cashback has FinPay paid?
transactions_merchants["cashback"].sum()

np.float64(14931.98)

In [383]:
#Which merchant gave the highest cashback?
transactions_merchants.groupby("merchant_name")["cashback"].sum().sort_values(ascending=False)

merchant_name
Merchant2     1008.61
Merchant16     985.09
Merchant18     902.83
Merchant20     900.87
Merchant15     879.22
Merchant3      842.31
Merchant10     841.38
Merchant5      809.36
Merchant19     805.63
Merchant17     733.94
Merchant13     727.70
Merchant4      709.91
Merchant6      705.75
Merchant11     691.00
Merchant14     648.83
Merchant12     643.77
Merchant9      589.24
Merchant7      581.46
Merchant1      500.10
Merchant8      424.98
Name: cashback, dtype: float64

In [384]:
#Which merchant category gives the highest average cashback?
transactions_merchants.groupby("category")["cashback"].mean()

category
Electronics    32.485913
Grocery        30.670857
Restaurant     28.135096
Travel         28.930488
Name: cashback, dtype: float64

Transaction Analytics

In [386]:
#How many transactions were successful and failed?
transactions_merchants["transaction_status"].value_counts()

transaction_status
Success    251
Failed     249
Name: count, dtype: int64

In [400]:
#What is the transaction success rate?
successful_transaction = transactions_merchants["transaction_status"]=="Success"
total_transactions = len(transactions_merchants["transaction_status"])
transaction_success_rate = successful_transaction.sum()/total_transactions*100
transaction_success_rate

np.float64(50.2)

In [ ]:
#Export the merged dataset 
transactions_merchants.to_csv("transactions_merchant_master.csv",index=False)